!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 24 Mar 2026 19:29
!
! fem_module.f90
! module with FEM problem implementation
MODULE FEM_MODULE_B
  IMPLICIT NONE

CONTAINS
!  Differentiation of get_residuals in reverse (adjoint) mode:
!   gradient     of useful results: res d a
!   with respect to varying inputs: d a
  SUBROUTINE GET_RESIDUALS_B(n_bars, a, ab, d, db, res, resb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
    REAL :: ab(n_bars), db(n_bars)
! Output variables
    REAL :: res(n_bars)
    REAL :: resb(n_bars)
! Working variables
    INTEGER :: ii
    REAL :: k(n_bars, n_bars), f(n_bars), kd(n_bars)
    REAL :: kb(n_bars, n_bars), kdb(n_bars)
! EXECUTION
!!! Build stiffness matrix
    k = 0.0
! Contribution of the first bar
    k(1, 1) = a(1)
! Contribution of remaining bars
    DO ii=2,n_bars
      k(ii-1, ii-1) = k(ii-1, ii-1) + a(ii)
      k(ii-1, ii) = k(ii-1, ii) - a(ii)
      k(ii, ii-1) = k(ii, ii-1) - a(ii)
      k(ii, ii) = k(ii, ii) + a(ii)
    END DO
! Multiply by the 1/L_bar factor
! In this problem L_bar = 1/n_bars
    k = k*n_bars
!!! Build force vector (load/length = 1)
!!! Compute residuals
    kdb = 0.0
    kdb = resb
    CALL MATDOTVEC_B(n_bars, k, kb, d, db, kd, kdb)
    kb = n_bars*kb
    DO ii=n_bars,2,-1
      ab(ii) = ab(ii) + kb(ii, ii) + kb(ii-1, ii-1) - kb(ii, ii-1) - kb(&
&       ii-1, ii)
    END DO
    ab(1) = ab(1) + kb(1, 1)
  END SUBROUTINE GET_RESIDUALS_B

  SUBROUTINE GET_RESIDUALS(n_bars, a, d, res)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
! Output variables
    REAL, INTENT(OUT) :: res(n_bars)
! Working variables
    INTEGER :: ii
    REAL :: k(n_bars, n_bars), f(n_bars), kd(n_bars)
! EXECUTION
!!! Build stiffness matrix
    k = 0.0
! Contribution of the first bar
    k(1, 1) = a(1)
! Contribution of remaining bars
    DO ii=2,n_bars
      k(ii-1, ii-1) = k(ii-1, ii-1) + a(ii)
      k(ii-1, ii) = k(ii-1, ii) - a(ii)
      k(ii, ii-1) = k(ii, ii-1) - a(ii)
      k(ii, ii) = k(ii, ii) + a(ii)
    END DO
! Multiply by the 1/L_bar factor
! In this problem L_bar = 1/n_bars
    k = k*n_bars
!!! Build force vector (load/length = 1)
    f = 1.0/n_bars
    f(n_bars) = 0.5/n_bars
!!! Compute residuals
    CALL MATDOTVEC(n_bars, k, d, kd)
    res = kd - f
  END SUBROUTINE GET_RESIDUALS

!  Differentiation of get_functions in reverse (adjoint) mode:
!   gradient     of useful results: v c
!   with respect to varying inputs: d a
!===================================
  SUBROUTINE GET_FUNCTIONS_B(n_bars, a, ab, d, db, c, cb, v, vb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
    REAL :: ab(n_bars), db(n_bars)
! Output variables
    REAL :: c, v
    REAL :: cb, vb
! Working variables
    REAL :: f(n_bars)
    INTEGER :: ii
! EXECUTION
!!! Build force vector (load/length = 1)
    f = 1.0/n_bars
    f(n_bars) = 0.5/n_bars
!!! Compliance
!!! Volume
    vb = vb/n_bars
    db = 0.0
    ab = 0.0
    DO ii=n_bars,1,-1
      ab(ii) = ab(ii) + vb
      db(ii) = db(ii) + f(ii)*cb
    END DO
  END SUBROUTINE GET_FUNCTIONS_B

!===================================
  SUBROUTINE GET_FUNCTIONS(n_bars, a, d, c, v)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
! Output variables
    REAL, INTENT(OUT) :: c, v
! Working variables
    REAL :: f(n_bars)
    INTEGER :: ii
! EXECUTION
!!! Build force vector (load/length = 1)
    f = 1.0/n_bars
    f(n_bars) = 0.5/n_bars
!!! Compliance
    c = 0
!!! Volume
    v = 0
    DO ii=1,n_bars
      c = c + f(ii)*d(ii)
      v = v + a(ii)
    END DO
    v = v/n_bars
  END SUBROUTINE GET_FUNCTIONS

!  Differentiation of matdotvec in reverse (adjoint) mode:
!   gradient     of useful results: d kd
!   with respect to varying inputs: d k
!===================================
  SUBROUTINE MATDOTVEC_B(n, k, kb, d, db, kd, kdb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n
    REAL, INTENT(IN) :: k(n, n), d(n)
    REAL :: kb(n, n), db(n)
! Output variables
    REAL :: kd(n)
    REAL :: kdb(n)
! Working variables
    INTEGER :: ii
! EXECUTION
    kb = 0.0
    DO ii=n,1,-1
      kb(:, ii) = kb(:, ii) + d(ii)*kdb
      db(ii) = db(ii) + SUM(k(:, ii)*kdb)
    END DO
  END SUBROUTINE MATDOTVEC_B

!===================================
  SUBROUTINE MATDOTVEC(n, k, d, kd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n
    REAL, INTENT(IN) :: k(n, n), d(n)
! Output variables
    REAL, INTENT(OUT) :: kd(n)
! Working variables
    INTEGER :: ii
! EXECUTION
    kd = 0.0
    DO ii=1,n
      kd = kd + k(:, ii)*d(ii)
    END DO
  END SUBROUTINE MATDOTVEC

!  Differentiation of main in reverse (adjoint) mode:
!   gradient     of useful results: res v c
!   with respect to varying inputs: res d v a c
!   RW status of diff variables: res:in-zero d:out v:in-zero a:out
!                c:in-zero
!===================================
  SUBROUTINE MAIN_B(n_bars, a, ab, d, db, res, resb, c, cb, v, vb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
    REAL :: ab(n_bars), db(n_bars)
! Output variables
    REAL :: res(n_bars)
    REAL :: resb(n_bars)
    REAL :: c, v
    REAL :: cb, vb
! EXECUTION
    CALL GET_FUNCTIONS_B(n_bars, a, ab, d, db, c, cb, v, vb)
    CALL GET_RESIDUALS_B(n_bars, a, ab, d, db, res, resb)
    resb = 0.0
    vb = 0.0
    cb = 0.0
  END SUBROUTINE MAIN_B

!===================================
  SUBROUTINE MAIN(n_bars, a, d, res, c, v)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
! Output variables
    REAL, INTENT(OUT) :: res(n_bars)
    REAL, INTENT(OUT) :: c, v
! EXECUTION
    CALL GET_RESIDUALS(n_bars, a, d, res)
    CALL GET_FUNCTIONS(n_bars, a, d, c, v)
  END SUBROUTINE MAIN

END MODULE FEM_MODULE_B

