from typing import Any

class FortranAsaModuleD:
    def asa_main(self, *args: Any, **kwargs: Any) -> tuple[Any, ...]: ...
    def asa_main_d(self, *args: Any, **kwargs: Any) -> tuple[Any, ...]: ...
    def transfer_disps(self, *args: Any, **kwargs: Any) -> Any: ...
    def transfer_disps_d(self, *args: Any, **kwargs: Any) -> Any: ...
    def transfer_forces(self, *args: Any, **kwargs: Any) -> Any: ...
    def transfer_forces_d(self, *args: Any, **kwargs: Any) -> Any: ...

asa_module_d: FortranAsaModuleD
