from typing import Any

class FortranAsaModule:
    def asa_main(self, *args: Any, **kwargs: Any) -> tuple[Any, ...]: ...
    def transfer_disps(self, *args: Any, **kwargs: Any) -> Any: ...
    def transfer_forces(self, *args: Any, **kwargs: Any) -> Any: ...

asa_module: FortranAsaModule
