from typing import Any

class FortranAsaModuleB:
    def asa_main(self, *args: Any, **kwargs: Any) -> tuple[Any, ...]: ...
    def asa_main_b(self, *args: Any, **kwargs: Any) -> tuple[Any, ...]: ...
    def transfer_disps(self, *args: Any, **kwargs: Any) -> Any: ...
    def transfer_disps_b(self, *args: Any, **kwargs: Any) -> Any: ...
    def transfer_forces(self, *args: Any, **kwargs: Any) -> Any: ...
    def transfer_forces_b(self, *args: Any, **kwargs: Any) -> Any: ...

asa_module_b: FortranAsaModuleB
