from typing import Any

class FortranMyModule2:
    def test_func(self, *args: Any, **kwargs: Any) -> Any: ...
    def test_func_complex(self, *args: Any, **kwargs: Any) -> Any: ...
    def test_func_deriv(self, *args: Any, **kwargs: Any) -> Any: ...

mymodule2: FortranMyModule2
