!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 20 Jun 2026 11:35
!
MODULE LLT_B
  IMPLICIT NONE

CONTAINS
!  Differentiation of llt_main in reverse (adjoint) mode:
!   gradient     of useful results: cd cl res_llt
!   with respect to varying inputs: twist gama cd cl res_llt
!   RW status of diff variables: twist:out gama:out cd:in-zero
!                cl:in-zero res_llt:in-zero
  SUBROUTINE LLT_MAIN_B(nelem, twist, twistb, gama, gamab, span, chord, &
&   cl0, cla, alpha, vinf, rho_air, res_llt, res_lltb, cl, clb, cd, cdb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: nelem
    REAL, INTENT(IN) :: twist(nelem), gama(nelem)
    REAL :: twistb(nelem), gamab(nelem)
    REAL, INTENT(IN) :: span, chord, cl0, cla, alpha, vinf, rho_air
! Output variables
    REAL :: res_llt(nelem)
    REAL :: res_lltb(nelem)
    REAL :: cl, cd
    REAL :: clb, cdb
! Working variables
    INTEGER :: ii
    REAL :: pi
    REAL :: panel_length, sref
! Spanwise locations of the horseshoe vortices
    REAL :: yc(nelem)
! Induced velocity at each horseshoe vortex and efective velocity at each wing section
    REAL :: wi(nelem), veff(nelem)
    REAL :: wib(nelem), veffb(nelem)
! Induced angle of attack and effective angle of attack at each wing section
    REAL :: alpha_ind(nelem), alpha_eff(nelem)
    REAL :: alpha_indb(nelem), alpha_effb(nelem)
! Section lift coefficient, sectional lift force and Kutta-Joukowski force at each wing section
    REAL :: cli(nelem), lsi(nelem), lki(nelem)
    REAL :: clib(nelem), lsib(nelem), lkib(nelem)
! Index array for the horseshoe vortices
    REAL :: idx(nelem)
    INTRINSIC ACOS
    INTRINSIC REAL
    INTRINSIC SUM
    INTRINSIC ATAN
    INTRINSIC SQRT
    INTRINSIC COS
    INTRINSIC SIN
    REAL :: result1
    REAL :: result1b
    REAL, DIMENSION(nelem) :: tempb
! EXECUTION
! Constants
    pi = ACOS(-1.0)
    panel_length = span/REAL(nelem)
    sref = span*chord
    idx = (/(1.0+(ii-1)*1.0, ii=1,nelem)/)
! ADD YOUR CODE HERE 
! Spanwise locations of the horseshoe vortices
    yc = 0.5*(panel_length-span) + (idx-1)*panel_length
! Compute the induced velocity at each horseshoe vortex using the Biot-Savart law
    DO ii=1,nelem
! Induced velocity at each horseshoe vortex
      result1 = SUM(gama/(4*(yc(ii)-yc)**2-panel_length**2))
      wi(ii) = panel_length/pi*result1
    END DO
! Compute the induced AoA, effective AoA and effective velocity at each wing section
! Induced angle of attack at each wing section
    alpha_ind = ATAN(wi/vinf)
! Effective angle of attack at each wing section
    alpha_eff = alpha + twist + alpha_ind
! Effective velocity at each wing section
    veff = SQRT(vinf**2 + wi**2)
! Section lift coefficient at each wing section
    cli = cl0 + cla*alpha_eff
! Compute lift force at each section 
! Sectional lift force at each wing section
! Kutta-Joukowski force at each wing section
    lki = rho_air*veff*gama
! Compute the LLT residuals at each wing section
! LLT residuals at each wing section
! Compute the total lift and drag coefficients of the wing
! Total lift coefficient of the wing
! Total drag coefficient of the wing
! END OF YOUR CODE
    lkib = 0.0
    alpha_indb = 0.0
    tempb = -(panel_length*cdb/(0.5*rho_air*sref*vinf**2))
    lkib = SIN(alpha_ind)*tempb
    alpha_indb = COS(alpha_ind)*lki*tempb
    tempb = panel_length*clb/(0.5*rho_air*sref*vinf**2)
    lkib = lkib + COS(alpha_ind)*tempb - res_lltb
    alpha_indb = alpha_indb - SIN(alpha_ind)*lki*tempb
    lsib = 0.0
    lsib = res_lltb
    gamab = 0.0
    veffb = 0.0
    gamab = veff*rho_air*lkib
    clib = 0.0
    tempb = rho_air*0.5*chord*lsib
    veffb = gama*rho_air*lkib + 2*veff*cli*tempb
    clib = veff**2*tempb
    alpha_effb = 0.0
    alpha_effb = cla*clib
    wib = 0.0
    twistb = 0.0
    twistb = alpha_effb
    alpha_indb = alpha_indb + alpha_effb
    WHERE (vinf**2 + wi**2 .EQ. 0.0) 
      wib = alpha_indb/(vinf*(1.0+(wi/vinf)**2))
    ELSEWHERE
      wib = 2*wi*veffb/(2.0*SQRT(vinf**2+wi**2)) + alpha_indb/(vinf*(1.0&
&       +(wi/vinf)**2))
    END WHERE
    DO ii=nelem,1,-1
      result1b = panel_length*wib(ii)/pi
      wib(ii) = 0.0
      gamab = gamab + result1b/(4*(yc(ii)-yc)**2-panel_length**2)
    END DO
    cdb = 0.0
    clb = 0.0
    res_lltb = 0.0
  END SUBROUTINE LLT_MAIN_B

  SUBROUTINE LLT_MAIN(nelem, twist, gama, span, chord, cl0, cla, alpha, &
&   vinf, rho_air, res_llt, cl, cd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: nelem
    REAL, INTENT(IN) :: twist(nelem), gama(nelem)
    REAL, INTENT(IN) :: span, chord, cl0, cla, alpha, vinf, rho_air
! Output variables
    REAL, INTENT(OUT) :: res_llt(nelem)
    REAL, INTENT(OUT) :: cl, cd
! Working variables
    INTEGER :: ii
    REAL :: pi
    REAL :: panel_length, sref
! Spanwise locations of the horseshoe vortices
    REAL :: yc(nelem)
! Induced velocity at each horseshoe vortex and efective velocity at each wing section
    REAL :: wi(nelem), veff(nelem)
! Induced angle of attack and effective angle of attack at each wing section
    REAL :: alpha_ind(nelem), alpha_eff(nelem)
! Section lift coefficient, sectional lift force and Kutta-Joukowski force at each wing section
    REAL :: cli(nelem), lsi(nelem), lki(nelem)
! Index array for the horseshoe vortices
    REAL :: idx(nelem)
    INTRINSIC ACOS
    INTRINSIC REAL
    INTRINSIC SUM
    INTRINSIC ATAN
    INTRINSIC SQRT
    INTRINSIC COS
    INTRINSIC SIN
    REAL :: result1
! EXECUTION
! Constants
    pi = ACOS(-1.0)
    panel_length = span/REAL(nelem)
    sref = span*chord
    idx = (/(1.0+(ii-1)*1.0, ii=1,nelem)/)
! ADD YOUR CODE HERE 
! Spanwise locations of the horseshoe vortices
    yc = 0.5*(panel_length-span) + (idx-1)*panel_length
! Compute the induced velocity at each horseshoe vortex using the Biot-Savart law
    DO ii=1,nelem
! Induced velocity at each horseshoe vortex
      result1 = SUM(gama/(4*(yc(ii)-yc)**2-panel_length**2))
      wi(ii) = panel_length/pi*result1
    END DO
! Compute the induced AoA, effective AoA and effective velocity at each wing section
! Induced angle of attack at each wing section
    alpha_ind = ATAN(wi/vinf)
! Effective angle of attack at each wing section
    alpha_eff = alpha + twist + alpha_ind
! Effective velocity at each wing section
    veff = SQRT(vinf**2 + wi**2)
! Section lift coefficient at each wing section
    cli = cl0 + cla*alpha_eff
! Compute lift force at each section 
! Sectional lift force at each wing section
    lsi = 0.5*rho_air*veff**2*chord*cli
! Kutta-Joukowski force at each wing section
    lki = rho_air*veff*gama
! Compute the LLT residuals at each wing section
! LLT residuals at each wing section
    res_llt = lsi - lki
! Compute the total lift and drag coefficients of the wing
! Total lift coefficient of the wing
    cl = SUM(lki*panel_length*COS(alpha_ind))/(0.5*rho_air*vinf**2*sref)
! Total drag coefficient of the wing
    cd = -(SUM(lki*panel_length*SIN(alpha_ind))/(0.5*rho_air*vinf**2*&
&     sref))
! END OF YOUR CODE
  END SUBROUTINE LLT_MAIN

END MODULE LLT_B

