!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 24 Mar 2026 19:29
!
! mymodule2.f90
! module with a multivariable function for derivative calculation
MODULE MYMODULE2_B
  IMPLICIT NONE

CONTAINS
!  Differentiation of test_func in reverse (adjoint) mode:
!   gradient     of useful results: f
!   with respect to varying inputs: f x y z
!   RW status of diff variables: f:in-zero x:out y:out z:out
  SUBROUTINE TEST_FUNC_B(x, xb, y, yb, z, zb, f, fb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: x, y, z
    REAL :: xb, yb, zb
    REAL :: f
    REAL :: fb
    REAL :: a
    REAL :: ab
    INTRINSIC COS
    a = y*COS(x) + z
    ab = 2*a*fb
    xb = -(2.0*fb/x**2) - SIN(x)*y*ab
    yb = COS(x)*ab
    zb = ab
    fb = 0.0
  END SUBROUTINE TEST_FUNC_B

  SUBROUTINE TEST_FUNC(x, y, z, f)
    IMPLICIT NONE
    REAL, INTENT(IN) :: x, y, z
    REAL, INTENT(OUT) :: f
    REAL :: a
    INTRINSIC COS
    a = y*COS(x) + z
    f = a**2 + 2.0/x
  END SUBROUTINE TEST_FUNC

!===================================
  SUBROUTINE TEST_FUNC_COMPLEX(x, y, z, f)
    IMPLICIT NONE
    COMPLEX, INTENT(IN) :: x, y, z
    COMPLEX, INTENT(OUT) :: f
    COMPLEX :: a
    INTRINSIC COS
    a = y*COS(x) + z
    f = a**2 + 2.0/x
  END SUBROUTINE TEST_FUNC_COMPLEX

!===================================
  SUBROUTINE TEST_FUNC_DERIV(x, y, z, dfdx, dfdy, dfdz)
    IMPLICIT NONE
    REAL, INTENT(IN) :: x, y, z
    REAL, INTENT(OUT) :: dfdx, dfdy, dfdz
    INTRINSIC SIN
    INTRINSIC COS
    dfdx = -(y**2*SIN(2.0*x)) - 2.0*y*z*SIN(x) - 2.0/x**2
    dfdy = 2*y*COS(x)**2 + 2.0*z*COS(x)
    dfdz = 2.0*y*COS(x) + 2.0*z
  END SUBROUTINE TEST_FUNC_DERIV

!===================================
  SUBROUTINE TEST_FUNC_MD(x, xd, y, yd, z, zd, f, fd)
    IMPLICIT NONE
    REAL, INTENT(IN) :: x, y, z
! Necessário adicionar input para as derivadas (sementes)
    REAL, INTENT(IN) :: xd, yd, zd
    REAL, INTENT(OUT) :: f
    REAL, INTENT(OUT) :: fd
    REAL :: a
    REAL :: ad
    INTRINSIC COS
    INTRINSIC SIN
! Linha original
    a = y*COS(x) + z
! Linha para derivada
    ad = -(y*SIN(x)*xd) + COS(x)*yd + zd
! Linha original
    f = a**2 + 2.0/x
! Linha para derivada
    fd = 2.0*a*ad - 2.0/x**2*xd
  END SUBROUTINE TEST_FUNC_MD

!===================================
  SUBROUTINE TEST_FUNC_MB(x, xb, y, yb, z, zb, f, fb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: x, y, z
! toda variável original vai ter uma versão barra
    REAL, INTENT(OUT) :: xb, yb, zb
    REAL, INTENT(OUT) :: f
    REAL, INTENT(IN) :: fb
    REAL :: a
    REAL :: ab
    INTRINSIC COS
    INTRINSIC SIN
! Forward pass
    a = y*COS(x) + z
    f = a**2 + 2.0/x
! Reverse pass
! Initialize seeds
    xb = 0.0
    yb = 0.0
    zb = 0.0
    ab = 0.0
! Linha 2: f = a**2 + 2.0/x
    xb = xb - 2.0/x**2*fb
    ab = ab + 2*a*fb
! Linha 1: a = y*cos(x) + z
    xb = xb - y*SIN(x)*ab
    yb = yb + COS(x)*ab
    zb = zb + 1.0*ab
  END SUBROUTINE TEST_FUNC_MB

END MODULE MYMODULE2_B

