!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 24 Mar 2026 19:29
!
MODULE ASA_MODULE_D
  IMPLICIT NONE
  REAL, SAVE :: zero=0.0
  REAL, SAVE :: pi=3.1415926535897932384626
  REAL, SAVE :: eps=EPSILON(zero)

CONTAINS
!  Differentiation of transfer_disps in forward (tangent) mode:
!   variations   of useful results: xllt
!   with respect to varying inputs: d
  SUBROUTINE TRANSFER_DISPS_D(n_nodes, xfem, d, dd, xllt, xlltd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_nodes
    REAL, INTENT(IN) :: xfem(3, n_nodes), d(2*n_nodes)
    REAL, INTENT(IN) :: dd(2*n_nodes)
! Output variables
    REAL, INTENT(OUT) :: xllt(3, n_nodes)
    REAL, INTENT(OUT) :: xlltd(3, n_nodes)
! EXECUTION
! Copy Xfem to Xllt, but just apply displacements in the z direction
    xllt(1, :) = xfem(1, :)
    xllt(2, :) = xfem(2, :)
    xlltd = 0.0
    xlltd(3, :) = dd(::2)
    xllt(3, :) = xfem(3, :) + d(::2)
  END SUBROUTINE TRANSFER_DISPS_D

  SUBROUTINE TRANSFER_DISPS(n_nodes, xfem, d, xllt)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_nodes
    REAL, INTENT(IN) :: xfem(3, n_nodes), d(2*n_nodes)
! Output variables
    REAL, INTENT(OUT) :: xllt(3, n_nodes)
! EXECUTION
! Copy Xfem to Xllt, but just apply displacements in the z direction
    xllt(1, :) = xfem(1, :)
    xllt(2, :) = xfem(2, :)
    xllt(3, :) = xfem(3, :) + d(::2)
  END SUBROUTINE TRANSFER_DISPS

!  Differentiation of transfer_forces in forward (tangent) mode:
!   variations   of useful results: f
!   with respect to varying inputs: loads
!============================================================
  SUBROUTINE TRANSFER_FORCES_D(n_nodes, xfem, loads, loadsd, f, fd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_nodes
    REAL, INTENT(IN) :: xfem(3, n_nodes), loads(n_nodes-1)
    REAL, INTENT(IN) :: loadsd(n_nodes-1)
! Output variables
    REAL, INTENT(OUT) :: f(2*n_nodes)
    REAL, INTENT(OUT) :: fd(2*n_nodes)
! Working variables
    REAL :: l(n_nodes-1)
    INTEGER :: ii
! EXECUTION
! Compute the panel lengths along the span axis (y-dim)
    l = xfem(2, 2:n_nodes) - xfem(2, 1:n_nodes-1)
! Initialize consistent force vector
    f = zero
    fd = 0.0
! Compute contributions of each horseshoe vortex to the consistent forces
    DO ii=1,n_nodes-1
      fd(2*ii-1) = fd(2*ii-1) + loadsd(ii)/2
      f(2*ii-1) = f(2*ii-1) + loads(ii)/2
      fd(2*ii) = fd(2*ii) + l(ii)*loadsd(ii)/12
      f(2*ii) = f(2*ii) + loads(ii)*l(ii)/12
      fd(2*ii+1) = fd(2*ii+1) + loadsd(ii)/2
      f(2*ii+1) = f(2*ii+1) + loads(ii)/2
      fd(2*ii+2) = fd(2*ii+2) - l(ii)*loadsd(ii)/12
      f(2*ii+2) = f(2*ii+2) - loads(ii)*l(ii)/12
    END DO
  END SUBROUTINE TRANSFER_FORCES_D

!============================================================
  SUBROUTINE TRANSFER_FORCES(n_nodes, xfem, loads, f)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_nodes
    REAL, INTENT(IN) :: xfem(3, n_nodes), loads(n_nodes-1)
! Output variables
    REAL, INTENT(OUT) :: f(2*n_nodes)
! Working variables
    REAL :: l(n_nodes-1)
    INTEGER :: ii
! EXECUTION
! Compute the panel lengths along the span axis (y-dim)
    l = xfem(2, 2:n_nodes) - xfem(2, 1:n_nodes-1)
! Initialize consistent force vector
    f = zero
! Compute contributions of each horseshoe vortex to the consistent forces
    DO ii=1,n_nodes-1
      f(2*ii-1) = f(2*ii-1) + loads(ii)/2
      f(2*ii) = f(2*ii) + loads(ii)*l(ii)/12
      f(2*ii+1) = f(2*ii+1) + loads(ii)/2
      f(2*ii+2) = f(2*ii+2) - loads(ii)*l(ii)/12
    END DO
  END SUBROUTINE TRANSFER_FORCES

!  Differentiation of asa_main in forward (tangent) mode:
!   variations   of useful results: liftexcess ksmargin resllt
!                fb margins resfem weight
!   with respect to varying inputs: d t twist gama
!   RW status of diff variables: liftexcess:out d:in t:in ksmargin:out
!                twist:in resllt:out fb:out margins:out resfem:out
!                gama:in weight:out
!============================================================
  SUBROUTINE ASA_MAIN_D(n_panels, gama, gamad, twist, twistd, chords, &
&   span, r, t, td, d, dd, cl0, cla, vinf, rhoair, e, rhomat, sigmay, &
&   pks, cd0, fixedmass, g, endurance, tsfc, loadfactor, resllt, reslltd&
&   , resfem, resfemd, liftexcess, liftexcessd, margins, marginsd, &
&   ksmargin, ksmargind, fb, fbd, weight, weightd, sref, cl)
! This subroutine computes the residuals of the coupled aerostructural
! problem.
!
! INPUTS
!
! n_panels: integer -> Number of horseshoe panels and beams (the same).
! Gama: real(n_panels) -> Circulation intensity of each horseshoe vortex.
! twist: real(n_panels) -> Array of local incidence angles.
! chords: real(n_panels) -> Array of local chords.
! span: real -> Wing span.
! r: real(n_panels) -> Radius of each beam element.
! t: real(n_panels) -> Wall thickness of each beam element.
! d: real(2*(n_panels+1)) -> Displacements values of all DOFs (including
!                           the constrained ones).
! cl0: real(n_panels) -> cl0 of each 2D section
! cla: real(n_panels) -> lift curve slope of each 2D section [1/rad]
! Vinf: real(3) -> Free-stream velocity vector
! rhoAir: real -> Air density
! E: real -> Young's module of the beam material.
! rhoMat: real -> Density of the beam material.
! sigmaY: real -> Yield stress of the beam material.
! pKS: real -> Constant of the KS functons used to aggregate stresses.
! CD0: real -> Parasite drag that will be added to the induced drag.
! fixedMass: real -> Fixed mass of the aircraft less the wing structure.
! g: real -> Acceleration of gravity.
! Endurance: real -> Desired endurance of the aircraft.
! TSFC: real -> Thrust specific fuel consumption of the engine.
! loadFactor: real -> Factor applied to the structural failure margin
!                     to consider a multiplicative factor in the loads.
!
! OUTPUTS
!
! resllt: real(n_panels) -> Residuals of the LLT method
! resfem: real(2*(n_panels+1)) -> Residuals of the FEM model
!                                 considering all DOFs (including the
!                                 constrained ones). The residuals
!                                 of the constrained DOFs are the
!                                 displacements themselves, so that the
!                                 solver drives them to zero. We
!                                 modify the K matrix in appy_cons to
!                                 achieve that.
! liftExcess: real -> Difference between the generated lift and the.
!                     aircraft weight. This value is normalized:
!                     liftExcess = Lift/Weigth - 1
! margins: real(2*n_panels) -> Margin from Von Mises stress at each node
!                              with respect to the yield stress.
!                              The margins are computed as:
!                              margin = 1.0 - sigma_vm/sigmaY
!                              Negative margins indicate failure.
!                              Internal nodes have two values
!                              corresponding to the beam sections on
!                              either side. KSmargin is the aggregation of
!                              these values.
! KSmargin: real -> Aggregated safety margin. This value
!                   is a conservative estimate of the minimum
!                   margin value in the structure. This estimate
!                   gets closer to the real value as we increase
!                   pKS, but this may lead to numerical issues.
! FB: real -> Fuel burn (in Force units).
! Weight: real -> Total weight of the aircraft (in Force units)
!                 (fixed weight + structure weight + fuel weight)
! Sref: real -> Area of all panels
! CL: real -> Lift coefficient (adimensionalized by Sref)
    USE LLT_MODULE_D, ONLY : llt_main, llt_main_d
    USE FEM_MODULE_D, ONLY : fem_main, fem_main_d
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_panels
    REAL, INTENT(IN) :: gama(n_panels), twist(n_panels)
    REAL, INTENT(IN) :: gamad(n_panels), twistd(n_panels)
    REAL, INTENT(IN) :: chords(n_panels)
    REAL, INTENT(IN) :: span
    REAL, INTENT(IN) :: r(n_panels), t(n_panels)
    REAL, INTENT(IN) :: td(n_panels)
    REAL, INTENT(IN) :: d(2*(n_panels+1))
    REAL, INTENT(IN) :: dd(2*(n_panels+1))
    REAL, INTENT(IN) :: cl0(n_panels), cla(n_panels), vinf(3), rhoair
    REAL, INTENT(IN) :: e, rhomat, sigmay, pks
    REAL, INTENT(IN) :: cd0, fixedmass, g, endurance, tsfc, loadfactor
! Output variables
    REAL, INTENT(OUT) :: resllt(n_panels), resfem(2*(n_panels+1))
    REAL, INTENT(OUT) :: reslltd(n_panels), resfemd(2*(n_panels+1))
    REAL, INTENT(OUT) :: liftexcess, margins(2*n_panels)
    REAL, INTENT(OUT) :: liftexcessd, marginsd(2*n_panels)
    REAL, INTENT(OUT) :: ksmargin, fb, weight, sref, cl
    REAL, INTENT(OUT) :: ksmargind, fbd, weightd
! Working variables
    REAL :: xfem(3, n_panels+1)
    REAL :: xllt(3, n_panels+1), cd, lift, drag
    REAL :: xlltd(3, n_panels+1), liftd, dragd
    REAL :: loads(n_panels), f(2*(n_panels+1)), structmass
    REAL :: loadsd(n_panels), fd(2*(n_panels+1)), structmassd
    REAL :: vinfm2
    INTEGER :: n_cons, conids(2)
    INTEGER :: ii, n_nodes
    INTRINSIC REAL
    INTRINSIC EXP
    REAL :: arg1
    REAL :: arg1d
    REAL :: srefd
    REAL :: temp
! EXECUTION
! Identify the indices of the structural DOFs that should
! be constrained, which corresponds to the central node.
! The first node of the wing has degrees of freedom 1 and 2,
! the second node has degrees of freedom 3 and 4, and so on.
! If we have n_panels elements, the degrees of freedom of the
! central node will be n_panels+1 and n_panels+2.
    n_cons = 2
    conids(1) = n_panels + 1
    conids(2) = n_panels + 2
    n_nodes = n_panels + 1
! ==================
! ADD YOUR CODE HERE
! ==================
! ==================
! STEP 1: Build the FEM nodes coordinates 
! ==================
    DO ii=1,n_nodes
      xfem(1, ii) = 0.0
      xfem(2, ii) = -(span/2.0) + (ii-1)*span/REAL(n_panels)
      xfem(3, ii) = 0.0
    END DO
! ==================
! STEP 2: Call modules
! ==================
! Transfer the displacements from the FEM model to the LLT model
    xlltd = 0.0
    CALL TRANSFER_DISPS_D(n_nodes, xfem, d, dd, xllt, xlltd)
! Call the LLT solver to compute the aerodynamic loads
! input variables
! output variables
    loadsd = 0.0
    CALL LLT_MAIN_D(n_panels, xllt, xlltd, gama, gamad, twist, twistd, &
&             chords, cl0, cla, vinf, rhoair, resllt, reslltd, sref, &
&             srefd, cl, cd, lift, liftd, drag, dragd, loads, loadsd)
! Transfer the aerodynamic loads from the LLT model to the FEM model
    fd = 0.0
    CALL TRANSFER_FORCES_D(n_nodes, xfem, loads, loadsd, f, fd)
! Call the FEM solver to compute the structural response
! input variables
! output variables
    CALL FEM_MAIN_D(n_panels, n_cons, xfem, r, t, td, f, fd, d, dd, e, &
&             rhomat, sigmay, pks, conids, resfem, resfemd, structmass, &
&             structmassd, margins, marginsd, ksmargin, ksmargind)
! ==================
! STEP 3: Convert margins by the loadfactor
! ==================
    marginsd = loadfactor*marginsd
    margins = loadfactor*margins + 1 - loadfactor
! ==================
! STEP 4: Convert KSmargins by the loadfactor
! ==================
    ksmargind = loadfactor*ksmargind
    ksmargin = loadfactor*ksmargin + 1 - loadfactor
! ==================
! STEP 5: Compute magnitude of Vinf
! ==================
    vinfm2 = vinf(1)**2 + vinf(2)**2 + vinf(3)**2
! ==================
! STEP 6: Compute total drag of the wing
! ==================
    temp = rhoair*vinfm2*cd0
    dragd = dragd + temp*srefd/2.0
    drag = drag + temp*(sref/2.0)
! ==================
! STEP 7: Compute Fuel Burn
! ==================
    arg1d = endurance*tsfc*(dragd-drag*liftd/lift)/lift
    arg1 = endurance*tsfc/(lift/drag)
    temp = EXP(arg1) - 1
    fbd = g*(temp*structmassd+(fixedmass+structmass)*EXP(arg1)*arg1d)
    fb = g*((fixedmass+structmass)*temp)
! ==================
! STEP 8: Compute Total weight
! ==================
    weightd = g*structmassd + fbd
    weight = (structmass+fixedmass)*g + fb
! ==================
! STEP 9: Compute Lift excess
! ==================
    liftexcessd = (liftd-lift*weightd/weight)/weight
    liftexcess = lift/weight - 1
  END SUBROUTINE ASA_MAIN_D

!============================================================
  SUBROUTINE ASA_MAIN(n_panels, gama, twist, chords, span, r, t, d, cl0&
&   , cla, vinf, rhoair, e, rhomat, sigmay, pks, cd0, fixedmass, g, &
&   endurance, tsfc, loadfactor, resllt, resfem, liftexcess, margins, &
&   ksmargin, fb, weight, sref, cl)
! This subroutine computes the residuals of the coupled aerostructural
! problem.
!
! INPUTS
!
! n_panels: integer -> Number of horseshoe panels and beams (the same).
! Gama: real(n_panels) -> Circulation intensity of each horseshoe vortex.
! twist: real(n_panels) -> Array of local incidence angles.
! chords: real(n_panels) -> Array of local chords.
! span: real -> Wing span.
! r: real(n_panels) -> Radius of each beam element.
! t: real(n_panels) -> Wall thickness of each beam element.
! d: real(2*(n_panels+1)) -> Displacements values of all DOFs (including
!                           the constrained ones).
! cl0: real(n_panels) -> cl0 of each 2D section
! cla: real(n_panels) -> lift curve slope of each 2D section [1/rad]
! Vinf: real(3) -> Free-stream velocity vector
! rhoAir: real -> Air density
! E: real -> Young's module of the beam material.
! rhoMat: real -> Density of the beam material.
! sigmaY: real -> Yield stress of the beam material.
! pKS: real -> Constant of the KS functons used to aggregate stresses.
! CD0: real -> Parasite drag that will be added to the induced drag.
! fixedMass: real -> Fixed mass of the aircraft less the wing structure.
! g: real -> Acceleration of gravity.
! Endurance: real -> Desired endurance of the aircraft.
! TSFC: real -> Thrust specific fuel consumption of the engine.
! loadFactor: real -> Factor applied to the structural failure margin
!                     to consider a multiplicative factor in the loads.
!
! OUTPUTS
!
! resllt: real(n_panels) -> Residuals of the LLT method
! resfem: real(2*(n_panels+1)) -> Residuals of the FEM model
!                                 considering all DOFs (including the
!                                 constrained ones). The residuals
!                                 of the constrained DOFs are the
!                                 displacements themselves, so that the
!                                 solver drives them to zero. We
!                                 modify the K matrix in appy_cons to
!                                 achieve that.
! liftExcess: real -> Difference between the generated lift and the.
!                     aircraft weight. This value is normalized:
!                     liftExcess = Lift/Weigth - 1
! margins: real(2*n_panels) -> Margin from Von Mises stress at each node
!                              with respect to the yield stress.
!                              The margins are computed as:
!                              margin = 1.0 - sigma_vm/sigmaY
!                              Negative margins indicate failure.
!                              Internal nodes have two values
!                              corresponding to the beam sections on
!                              either side. KSmargin is the aggregation of
!                              these values.
! KSmargin: real -> Aggregated safety margin. This value
!                   is a conservative estimate of the minimum
!                   margin value in the structure. This estimate
!                   gets closer to the real value as we increase
!                   pKS, but this may lead to numerical issues.
! FB: real -> Fuel burn (in Force units).
! Weight: real -> Total weight of the aircraft (in Force units)
!                 (fixed weight + structure weight + fuel weight)
! Sref: real -> Area of all panels
! CL: real -> Lift coefficient (adimensionalized by Sref)
    USE LLT_MODULE_D, ONLY : llt_main
    USE FEM_MODULE_D, ONLY : fem_main
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_panels
    REAL, INTENT(IN) :: gama(n_panels), twist(n_panels)
    REAL, INTENT(IN) :: chords(n_panels)
    REAL, INTENT(IN) :: span
    REAL, INTENT(IN) :: r(n_panels), t(n_panels)
    REAL, INTENT(IN) :: d(2*(n_panels+1))
    REAL, INTENT(IN) :: cl0(n_panels), cla(n_panels), vinf(3), rhoair
    REAL, INTENT(IN) :: e, rhomat, sigmay, pks
    REAL, INTENT(IN) :: cd0, fixedmass, g, endurance, tsfc, loadfactor
! Output variables
    REAL, INTENT(OUT) :: resllt(n_panels), resfem(2*(n_panels+1))
    REAL, INTENT(OUT) :: liftexcess, margins(2*n_panels)
    REAL, INTENT(OUT) :: ksmargin, fb, weight, sref, cl
! Working variables
    REAL :: xfem(3, n_panels+1)
    REAL :: xllt(3, n_panels+1), cd, lift, drag
    REAL :: loads(n_panels), f(2*(n_panels+1)), structmass
    REAL :: vinfm2
    INTEGER :: n_cons, conids(2)
    INTEGER :: ii, n_nodes
    INTRINSIC REAL
    INTRINSIC EXP
    REAL :: arg1
! EXECUTION
! Identify the indices of the structural DOFs that should
! be constrained, which corresponds to the central node.
! The first node of the wing has degrees of freedom 1 and 2,
! the second node has degrees of freedom 3 and 4, and so on.
! If we have n_panels elements, the degrees of freedom of the
! central node will be n_panels+1 and n_panels+2.
    n_cons = 2
    conids(1) = n_panels + 1
    conids(2) = n_panels + 2
    n_nodes = n_panels + 1
! ==================
! ADD YOUR CODE HERE
! ==================
! ==================
! STEP 1: Build the FEM nodes coordinates 
! ==================
    DO ii=1,n_nodes
      xfem(1, ii) = 0.0
      xfem(2, ii) = -(span/2.0) + (ii-1)*span/REAL(n_panels)
      xfem(3, ii) = 0.0
    END DO
! ==================
! STEP 2: Call modules
! ==================
! Transfer the displacements from the FEM model to the LLT model
    CALL TRANSFER_DISPS(n_nodes, xfem, d, xllt)
! Call the LLT solver to compute the aerodynamic loads
! input variables
! output variables
    CALL LLT_MAIN(n_panels, xllt, gama, twist, chords, cl0, cla, vinf, &
&           rhoair, resllt, sref, cl, cd, lift, drag, loads)
! Transfer the aerodynamic loads from the LLT model to the FEM model
    CALL TRANSFER_FORCES(n_nodes, xfem, loads, f)
! Call the FEM solver to compute the structural response
! input variables
! output variables
    CALL FEM_MAIN(n_panels, n_cons, xfem, r, t, f, d, e, rhomat, sigmay&
&           , pks, conids, resfem, structmass, margins, ksmargin)
! ==================
! STEP 3: Convert margins by the loadfactor
! ==================
    margins = loadfactor*margins + 1 - loadfactor
! ==================
! STEP 4: Convert KSmargins by the loadfactor
! ==================
    ksmargin = loadfactor*ksmargin + 1 - loadfactor
! ==================
! STEP 5: Compute magnitude of Vinf
! ==================
    vinfm2 = vinf(1)**2 + vinf(2)**2 + vinf(3)**2
! ==================
! STEP 6: Compute total drag of the wing
! ==================
    drag = drag + rhoair*vinfm2*cd0*sref/2.0
! ==================
! STEP 7: Compute Fuel Burn
! ==================
    arg1 = endurance*tsfc/(lift/drag)
    fb = (structmass+fixedmass)*g*(EXP(arg1)-1)
! ==================
! STEP 8: Compute Total weight
! ==================
    weight = (structmass+fixedmass)*g + fb
! ==================
! STEP 9: Compute Lift excess
! ==================
    liftexcess = lift/weight - 1
  END SUBROUTINE ASA_MAIN

END MODULE ASA_MODULE_D

