!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 24 Mar 2026 19:29
!
MODULE LLT_MODULE_D
  IMPLICIT NONE
  REAL, SAVE :: zero=0.0
  REAL, SAVE :: pi=3.1415926535897932384626
  REAL, SAVE :: eps=EPSILON(zero)

CONTAINS
!  Differentiation of induced_vel in forward (tangent) mode:
!   variations   of useful results: gamma_ind
!   with respect to varying inputs: xp x1 x2
  SUBROUTINE INDUCED_VEL_D(uinf, x1, x1d, x2, x2d, xp, xpd, gamma_ind, &
&   gamma_indd)
    IMPLICIT NONE
! Input variables
    REAL, INTENT(IN) :: uinf(3), x1(3), x2(3), xp(3)
    REAL, INTENT(IN) :: x1d(3), x2d(3), xpd(3)
! Output variables
    REAL, INTENT(OUT) :: gamma_ind(3)
    REAL, INTENT(OUT) :: gamma_indd(3)
! Working variables
    REAL :: r1(3), r2(3), v1(3), v2(3), v3(3)
    REAL :: r1d(3), r2d(3), v1d(3), v2d(3), v3d(3)
    REAL :: uinfcr1(3), uinfcr2(3), r1cr2(3)
    REAL :: uinfcr1d(3), uinfcr2d(3), r1cr2d(3)
    REAL :: r1m, r2m, uinfdr1, uinfdr2, r1dr2, den
    REAL :: r1md, r2md, uinfdr1d, uinfdr2d, r1dr2d, dend
    INTRINSIC ABS
    REAL :: abs0
    REAL, DIMENSION(3) :: uinfd
    REAL :: temp
    REAL, DIMENSION(3) :: temp0
! EXECUTION
! Compute vectors between the kinks and the point of interest
    r1d = xpd - x1d
    r1 = xp - x1
    r2d = xpd - x2d
    r2 = xp - x2
! Compute the magnitude of these vectors
    CALL NORM_D(r1, r1d, r1m, r1md)
    CALL NORM_D(r2, r2d, r2m, r2md)
! Compute cross products
    uinfcr1d = 0.0
    uinfd = 0.0
    CALL CROSS_D(uinf, uinfd, r1, r1d, uinfcr1, uinfcr1d)
    uinfcr2d = 0.0
    uinfd = 0.0
    CALL CROSS_D(uinf, uinfd, r2, r2d, uinfcr2, uinfcr2d)
    r1cr2d = 0.0
    CALL CROSS_D(r1, r1d, r2, r2d, r1cr2, r1cr2d)
! Compute dot products
    uinfd = 0.0
    CALL DOT_D(uinf, uinfd, r1, r1d, uinfdr1, uinfdr1d)
    uinfd = 0.0
    CALL DOT_D(uinf, uinfd, r2, r2d, uinfdr2, uinfdr2d)
    CALL DOT_D(r1, r1d, r2, r2d, r1dr2, r1dr2d)
! Compute contributions of each vortex segment
    temp = r2m*(r2m-uinfdr2)
    v1d = (uinfcr2d-uinfcr2*((r2m-uinfdr2)*r2md+r2m*(r2md-uinfdr2d))/&
&     temp)/temp
    v1 = uinfcr2/temp
    dend = r2m*r1md + r1m*r2md + r1dr2d
    den = r1m*r2m + r1dr2
    IF (den .GE. 0.) THEN
      abs0 = den
    ELSE
      abs0 = -den
    END IF
    IF (abs0 .GT. eps) THEN
      temp = r1m*r2m*den
      temp0 = (r1m+r2m)*r1cr2/temp
      v2d = (r1cr2*(r1md+r2md)+(r1m+r2m)*r1cr2d-temp0*(den*(r2m*r1md+r1m&
&       *r2md)+r1m*r2m*dend))/temp
      v2 = temp0
    ELSE
! Bound vortex induces no velocity along its length
      v2 = zero
      v2d = 0.0
    END IF
    temp = r1m*(r1m-uinfdr1)
    v3d = -((uinfcr1d-uinfcr1*((r1m-uinfdr1)*r1md+r1m*(r1md-uinfdr1d))/&
&     temp)/temp)
    v3 = -(uinfcr1/temp)
! Compute overall induced velocity (without the circulation: V/gamma)
    gamma_indd = 0.25*(v1d+v2d+v3d)/pi
    gamma_ind = 0.25*(v1+v2+v3)/pi
  END SUBROUTINE INDUCED_VEL_D

  SUBROUTINE INDUCED_VEL(uinf, x1, x2, xp, gamma_ind)
    IMPLICIT NONE
! Input variables
    REAL, INTENT(IN) :: uinf(3), x1(3), x2(3), xp(3)
! Output variables
    REAL, INTENT(OUT) :: gamma_ind(3)
! Working variables
    REAL :: r1(3), r2(3), v1(3), v2(3), v3(3)
    REAL :: uinfcr1(3), uinfcr2(3), r1cr2(3)
    REAL :: r1m, r2m, uinfdr1, uinfdr2, r1dr2, den
    INTRINSIC ABS
    REAL :: abs0
! EXECUTION
! Compute vectors between the kinks and the point of interest
    r1 = xp - x1
    r2 = xp - x2
! Compute the magnitude of these vectors
    CALL NORM(r1, r1m)
    CALL NORM(r2, r2m)
! Compute cross products
    CALL CROSS(uinf, r1, uinfcr1)
    CALL CROSS(uinf, r2, uinfcr2)
    CALL CROSS(r1, r2, r1cr2)
! Compute dot products
    CALL DOT(uinf, r1, uinfdr1)
    CALL DOT(uinf, r2, uinfdr2)
    CALL DOT(r1, r2, r1dr2)
! Compute contributions of each vortex segment
    v1 = uinfcr2/r2m/(r2m-uinfdr2)
    den = r1m*r2m + r1dr2
    IF (den .GE. 0.) THEN
      abs0 = den
    ELSE
      abs0 = -den
    END IF
    IF (abs0 .GT. eps) THEN
      v2 = (r1m+r2m)*r1cr2/r1m/r2m/den
    ELSE
! Bound vortex induces no velocity along its length
      v2 = zero
    END IF
    v3 = -(uinfcr1/r1m/(r1m-uinfdr1))
! Compute overall induced velocity (without the circulation: V/gamma)
    gamma_ind = 0.25*(v1+v2+v3)/pi
  END SUBROUTINE INDUCED_VEL

!  Differentiation of get_aic_matrix in forward (tangent) mode:
!   variations   of useful results: aic
!   with respect to varying inputs: x
!============================================================
  SUBROUTINE GET_AIC_MATRIX_D(n_vort, x, xd, uinf, aic, aicd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: uinf(3)
! Output variables
    REAL, INTENT(OUT) :: aic(3, n_vort, n_vort)
    REAL, INTENT(OUT) :: aicd(3, n_vort, n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: x1(3), x2(3), xcen(3), gamma_ind(3)
    REAL :: x1d(3), x2d(3), xcend(3), gamma_indd(3)
    aicd = 0.0
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1d = xd(:, ii)
      x1 = x(:, ii)
      x2d = xd(:, ii+1)
      x2 = x(:, ii+1)
! Compute the center of the bound vortex
      xcend = 0.5*(x1d+x2d)
      xcen = 0.5*(x1+x2)
! Loop over all bound vortices to compute the influence coefficients
      DO jj=1,n_vort
! Get kink coordinates of the current vortex
        x1d = xd(:, jj)
        x1 = x(:, jj)
        x2d = xd(:, jj+1)
        x2 = x(:, jj+1)
! The induced velocity, normalized by gamma, is the influence
! coefficient.
        gamma_indd = 0.0
        CALL INDUCED_VEL_D(uinf, x1, x1d, x2, x2d, xcen, xcend, &
&                    gamma_ind, gamma_indd)
        aicd(:, jj, ii) = gamma_indd
        aic(:, jj, ii) = gamma_ind
      END DO
    END DO
  END SUBROUTINE GET_AIC_MATRIX_D

!============================================================
  SUBROUTINE GET_AIC_MATRIX(n_vort, x, uinf, aic)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: uinf(3)
! Output variables
    REAL, INTENT(OUT) :: aic(3, n_vort, n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: x1(3), x2(3), xcen(3), gamma_ind(3)
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1 = x(:, ii)
      x2 = x(:, ii+1)
! Compute the center of the bound vortex
      xcen = 0.5*(x1+x2)
! Loop over all bound vortices to compute the influence coefficients
      DO jj=1,n_vort
! Get kink coordinates of the current vortex
        x1 = x(:, jj)
        x2 = x(:, jj+1)
! The induced velocity, normalized by gamma, is the influence
! coefficient.
        CALL INDUCED_VEL(uinf, x1, x2, xcen, gamma_ind)
        aic(:, jj, ii) = gamma_ind
      END DO
    END DO
  END SUBROUTINE GET_AIC_MATRIX

!  Differentiation of get_geom_vectors in forward (tangent) mode:
!   variations   of useful results: uai uni si areas
!   with respect to varying inputs: x twist
!============================================================
  SUBROUTINE GET_GEOM_VECTORS_D(n_vort, x, xd, twist, twistd, chords, &
&   uai, uaid, uni, unid, si, sid, areas, areasd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: twist(n_vort), chords(n_vort)
    REAL, INTENT(IN) :: twistd(n_vort)
! Output variables
    REAL, INTENT(OUT) :: uai(3, n_vort), uni(3, n_vort)
    REAL, INTENT(OUT) :: uaid(3, n_vort), unid(3, n_vort)
    REAL, INTENT(OUT) :: si(3, n_vort), areas(n_vort)
    REAL, INTENT(OUT) :: sid(3, n_vort), areasd(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: x1(3), x2(3), usi(3), ni(3)
    REAL :: x1d(3), x2d(3), usid(3), nid(3)
    REAL :: nim, sim
    REAL :: nimd, simd
    INTRINSIC COS
    INTRINSIC SIN
    uaid = 0.0
    unid = 0.0
    sid = 0.0
    areasd = 0.0
    nid = 0.0
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1d = xd(:, ii)
      x1 = x(:, ii)
      x2d = xd(:, ii+1)
      x2 = x(:, ii+1)
! Compute the vector along the local span
      sid(:, ii) = x2d - x1d
      si(:, ii) = x2 - x1
      usid = 0.0
      CALL NORMALIZE_D(si(:, ii), sid(:, ii), usi, usid)
! Create a unitary vector along the chordline
! pointing to the trailing edge
      uaid(1, ii) = -(SIN(twist(ii))*twistd(ii))
      uai(1, ii) = COS(twist(ii))
      uaid(2, ii) = 0.0
      uai(2, ii) = zero
      uaid(3, ii) = -(COS(twist(ii))*twistd(ii))
      uai(3, ii) = -SIN(twist(ii))
! Get the normal vector as the normal between the span
! and the chord vector
      CALL CROSS_D(uai(:, ii), uaid(:, ii), usi, usid, ni, nid)
      CALL NORMALIZE_D(ni, nid, uni(:, ii), unid(:, ii))
! Compute the local area of the panel.
! The norm of the normal vector is the sine of the angle.
      CALL NORM_D(ni, nid, nim, nimd)
      CALL NORM_D(si(:, ii), sid(:, ii), sim, simd)
      areasd(ii) = chords(ii)*(sim*nimd+nim*simd)
      areas(ii) = nim*chords(ii)*sim
    END DO
  END SUBROUTINE GET_GEOM_VECTORS_D

!============================================================
  SUBROUTINE GET_GEOM_VECTORS(n_vort, x, twist, chords, uai, uni, si, &
&   areas)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: twist(n_vort), chords(n_vort)
! Output variables
    REAL, INTENT(OUT) :: uai(3, n_vort), uni(3, n_vort)
    REAL, INTENT(OUT) :: si(3, n_vort), areas(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: x1(3), x2(3), usi(3), ni(3)
    REAL :: nim, sim
    INTRINSIC COS
    INTRINSIC SIN
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1 = x(:, ii)
      x2 = x(:, ii+1)
! Compute the vector along the local span
      si(:, ii) = x2 - x1
      CALL NORMALIZE(si(:, ii), usi)
! Create a unitary vector along the chordline
! pointing to the trailing edge
      uai(1, ii) = COS(twist(ii))
      uai(2, ii) = zero
      uai(3, ii) = -SIN(twist(ii))
! Get the normal vector as the normal between the span
! and the chord vector
      CALL CROSS(uai(:, ii), usi, ni)
      CALL NORMALIZE(ni, uni(:, ii))
! Compute the local area of the panel.
! The norm of the normal vector is the sine of the angle.
      CALL NORM(ni, nim)
      CALL NORM(si(:, ii), sim)
      areas(ii) = nim*chords(ii)*sim
    END DO
  END SUBROUTINE GET_GEOM_VECTORS

!  Differentiation of get_local_vels in forward (tangent) mode:
!   variations   of useful results: vlocal alphalocal
!   with respect to varying inputs: uai uni gama aic
!============================================================
  SUBROUTINE GET_LOCAL_VELS_D(n_vort, gama, gamad, aic, aicd, vinf, uai&
&   , uaid, uni, unid, vlocal, vlocald, alphalocal, alphalocald)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: gama(n_vort), aic(3, n_vort, n_vort)
    REAL, INTENT(IN) :: gamad(n_vort), aicd(3, n_vort, n_vort)
    REAL, INTENT(IN) :: vinf(3), uai(3, n_vort), uni(3, n_vort)
    REAL, INTENT(IN) :: uaid(3, n_vort), unid(3, n_vort)
! Output variables
    REAL, INTENT(OUT) :: vlocal(3, n_vort), alphalocal(n_vort)
    REAL, INTENT(OUT) :: vlocald(3, n_vort), alphalocald(n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: num, den
    REAL :: numd, dend
    INTRINSIC ATAN
    REAL :: temp
    vlocald = 0.0
    alphalocald = 0.0
! EXECUTION
! Do the matrix operation
    DO ii=1,n_vort
! Start with the free-strem contribution
      vlocald(:, ii) = 0.0
      vlocal(:, ii) = vinf
! Now add the velocities induced by each vortex
      DO jj=1,n_vort
        vlocald(:, ii) = vlocald(:, ii) + gama(jj)*aicd(:, jj, ii) + aic&
&         (:, jj, ii)*gamad(jj)
        vlocal(:, ii) = vlocal(:, ii) + aic(:, jj, ii)*gama(jj)
      END DO
! Compute the local angle of attack
      CALL DOT_D(vlocal(:, ii), vlocald(:, ii), uni(:, ii), unid(:, ii)&
&          , num, numd)
      CALL DOT_D(vlocal(:, ii), vlocald(:, ii), uai(:, ii), uaid(:, ii)&
&          , den, dend)
      temp = num/den
      alphalocald(ii) = (numd-temp*dend)/((1.0+temp**2)*den)
      alphalocal(ii) = ATAN(temp)
    END DO
  END SUBROUTINE GET_LOCAL_VELS_D

!============================================================
  SUBROUTINE GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&   alphalocal)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: gama(n_vort), aic(3, n_vort, n_vort)
    REAL, INTENT(IN) :: vinf(3), uai(3, n_vort), uni(3, n_vort)
! Output variables
    REAL, INTENT(OUT) :: vlocal(3, n_vort), alphalocal(n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: num, den
    INTRINSIC ATAN
! EXECUTION
! Do the matrix operation
    DO ii=1,n_vort
! Start with the free-strem contribution
      vlocal(:, ii) = vinf
! Now add the velocities induced by each vortex
      DO jj=1,n_vort
        vlocal(:, ii) = vlocal(:, ii) + aic(:, jj, ii)*gama(jj)
      END DO
! Compute the local angle of attack
      CALL DOT(vlocal(:, ii), uni(:, ii), num)
      CALL DOT(vlocal(:, ii), uai(:, ii), den)
      alphalocal(ii) = ATAN(num/den)
    END DO
  END SUBROUTINE GET_LOCAL_VELS

!  Differentiation of compute_circulation_forces in forward (tangent) mode:
!   variations   of useful results: fcirc
!   with respect to varying inputs: vlocal gama si
!============================================================
  SUBROUTINE COMPUTE_CIRCULATION_FORCES_D(n_vort, rho, vlocal, vlocald, &
&   si, sid, gama, gamad, fcirc, fcircd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, vlocal(3, n_vort), si(3, n_vort)
    REAL, INTENT(IN) :: vlocald(3, n_vort), sid(3, n_vort)
    REAL, INTENT(IN) :: gama(n_vort)
    REAL, INTENT(IN) :: gamad(n_vort)
! Output variables
    REAL, INTENT(OUT) :: fcirc(3, n_vort)
    REAL, INTENT(OUT) :: fcircd(3, n_vort)
! Working variables
    INTEGER :: ii
    REAL :: li(3)
    REAL :: lid(3)
    fcircd = 0.0
    lid = 0.0
! EXECUTION
    DO ii=1,n_vort
! L=rho*V*gamma*l
      CALL CROSS_D(vlocal(:, ii), vlocald(:, ii), si(:, ii), sid(:, ii)&
&            , li, lid)
      fcircd(:, ii) = rho*(li*gamad(ii)+gama(ii)*lid)
      fcirc(:, ii) = rho*gama(ii)*li
    END DO
  END SUBROUTINE COMPUTE_CIRCULATION_FORCES_D

!============================================================
  SUBROUTINE COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, &
&   fcirc)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, vlocal(3, n_vort), si(3, n_vort)
    REAL, INTENT(IN) :: gama(n_vort)
! Output variables
    REAL, INTENT(OUT) :: fcirc(3, n_vort)
! Working variables
    INTEGER :: ii
    REAL :: li(3)
! EXECUTION
    DO ii=1,n_vort
! L=rho*V*gamma*l
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
      fcirc(:, ii) = rho*gama(ii)*li
    END DO
  END SUBROUTINE COMPUTE_CIRCULATION_FORCES

!  Differentiation of compute_airfoil_forces in forward (tangent) mode:
!   variations   of useful results: fairf
!   with respect to varying inputs: vlocal si areas alphalocal
!============================================================
  SUBROUTINE COMPUTE_AIRFOIL_FORCES_D(n_vort, rho, cl0, cla, areas, &
&   areasd, vlocal, vlocald, alphalocal, alphalocald, si, sid, fairf, &
&   fairfd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, cl0(n_vort), cla(n_vort), areas(n_vort)
    REAL, INTENT(IN) :: areasd(n_vort)
    REAL, INTENT(IN) :: vlocal(3, n_vort), alphalocal(n_vort), si(3, &
&   n_vort)
    REAL, INTENT(IN) :: vlocald(3, n_vort), alphalocald(n_vort), sid(3, &
&   n_vort)
! Output variables
    REAL, INTENT(OUT) :: fairf(3, n_vort)
    REAL, INTENT(OUT) :: fairfd(3, n_vort)
! Working variables
    REAL :: fairfm, cl, li(3), uli(3), vlocalm
    REAL :: fairfmd, cld, lid(3), ulid(3), vlocalmd
    INTEGER :: ii
    fairfd = 0.0
    lid = 0.0
! EXECUTION
! Loop over all horseshoe vortices
    DO ii=1,n_vort
! Compute the magnitude of the force given by the 2D section
! L = 0.5*Vlocal²*area*cl
      cld = cla(ii)*alphalocald(ii)
      cl = cl0(ii) + alphalocal(ii)*cla(ii)
      CALL NORM_D(vlocal(:, ii), vlocald(:, ii), vlocalm, vlocalmd)
      fairfmd = rho*0.5*(areas(ii)*cl*2*vlocalm*vlocalmd+vlocalm**2*(cl*&
&       areasd(ii)+areas(ii)*cld))
      fairfm = 0.5*rho*vlocalm*vlocalm*areas(ii)*cl
! Get normalized lift direction
      CALL CROSS_D(vlocal(:, ii), vlocald(:, ii), si(:, ii), sid(:, ii)&
&            , li, lid)
      ulid = 0.0
      CALL NORMALIZE_D(li, lid, uli, ulid)
! Store the force
      fairfd(:, ii) = uli*fairfmd + fairfm*ulid
      fairf(:, ii) = fairfm*uli
    END DO
  END SUBROUTINE COMPUTE_AIRFOIL_FORCES_D

!============================================================
  SUBROUTINE COMPUTE_AIRFOIL_FORCES(n_vort, rho, cl0, cla, areas, vlocal&
&   , alphalocal, si, fairf)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, cl0(n_vort), cla(n_vort), areas(n_vort)
    REAL, INTENT(IN) :: vlocal(3, n_vort), alphalocal(n_vort), si(3, &
&   n_vort)
! Output variables
    REAL, INTENT(OUT) :: fairf(3, n_vort)
! Working variables
    REAL :: fairfm, cl, li(3), uli(3), vlocalm
    INTEGER :: ii
! EXECUTION
! Loop over all horseshoe vortices
    DO ii=1,n_vort
! Compute the magnitude of the force given by the 2D section
! L = 0.5*Vlocal²*area*cl
      cl = cl0(ii) + alphalocal(ii)*cla(ii)
      CALL NORM(vlocal(:, ii), vlocalm)
      fairfm = 0.5*rho*vlocalm*vlocalm*areas(ii)*cl
! Get normalized lift direction
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
      CALL NORMALIZE(li, uli)
! Store the force
      fairf(:, ii) = fairfm*uli
    END DO
  END SUBROUTINE COMPUTE_AIRFOIL_FORCES

!  Differentiation of get_residuals in forward (tangent) mode:
!   variations   of useful results: res
!   with respect to varying inputs: x twist gama
!============================================================
  SUBROUTINE GET_RESIDUALS_D0(n_vort, x, xd, gama, gamad, twist, twistd&
&   , chords, cl0, cla, vinf, rho, res, resd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL, INTENT(IN) :: gamad(n_vort), twistd(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort)
    REAL, INTENT(OUT) :: resd(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: aicd(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: uaid(3, n_vort), unid(3, n_vort), sid(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: areasd(n_vort), vlocald(3, n_vort), alphalocald(n_vort)
    REAL :: fcirc(3, n_vort), fairf(3, n_vort), deltaf(3)
    REAL :: fcircd(3, n_vort), fairfd(3, n_vort), deltafd(3)
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    aicd = 0.0
    CALL GET_AIC_MATRIX_D(n_vort, x, xd, uinf, aic, aicd)
! Get geometric vectors
    areasd = 0.0
    sid = 0.0
    unid = 0.0
    uaid = 0.0
    CALL GET_GEOM_VECTORS_D(n_vort, x, xd, twist, twistd, chords, uai, &
&                     uaid, uni, unid, si, sid, areas, areasd)
! Get induced velocities
    alphalocald = 0.0
    vlocald = 0.0
    CALL GET_LOCAL_VELS_D(n_vort, gama, gamad, aic, aicd, vinf, uai, &
&                   uaid, uni, unid, vlocal, vlocald, alphalocal, &
&                   alphalocald)
! Get circulation forces
    fcircd = 0.0
    CALL COMPUTE_CIRCULATION_FORCES_D(n_vort, rho, vlocal, vlocald, si, &
&                               sid, gama, gamad, fcirc, fcircd)
! Get airfoil forces
    fairfd = 0.0
    CALL COMPUTE_AIRFOIL_FORCES_D(n_vort, rho, cl0, cla, areas, areasd, &
&                           vlocal, vlocald, alphalocal, alphalocald, si&
&                           , sid, fairf, fairfd)
    resd = 0.0
! The residual is the difference between the forces for each horseshoe vortex
    DO ii=1,n_vort
! Get the difference in forces
      deltafd = fcircd(:, ii) - fairfd(:, ii)
      deltaf = fcirc(:, ii) - fairf(:, ii)
! The residual is the magnitude of the difference
      resd(ii) = 2*deltaf(1)*deltafd(1) + 2*deltaf(2)*deltafd(2) + 2*&
&       deltaf(3)*deltafd(3)
      res(ii) = deltaf(1)**2 + deltaf(2)**2 + deltaf(3)**2
    END DO
  END SUBROUTINE GET_RESIDUALS_D0

!============================================================
  SUBROUTINE GET_RESIDUALS(n_vort, x, gama, twist, chords, cl0, cla, &
&   vinf, rho, res)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: fcirc(3, n_vort), fairf(3, n_vort), deltaf(3)
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL GET_GEOM_VECTORS(n_vort, x, twist, chords, uai, uni, si, areas)
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get circulation forces
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Get airfoil forces
    CALL COMPUTE_AIRFOIL_FORCES(n_vort, rho, cl0, cla, areas, vlocal, &
&                         alphalocal, si, fairf)
! The residual is the difference between the forces for each horseshoe vortex
    DO ii=1,n_vort
! Get the difference in forces
      deltaf = fcirc(:, ii) - fairf(:, ii)
! The residual is the magnitude of the difference
      res(ii) = deltaf(1)**2 + deltaf(2)**2 + deltaf(3)**2
    END DO
  END SUBROUTINE GET_RESIDUALS

!  Differentiation of get_functions in forward (tangent) mode:
!   variations   of useful results: d loads l sref
!   with respect to varying inputs: x twist gama
!============================================================
  SUBROUTINE GET_FUNCTIONS_D0(n_vort, x, xd, gama, gamad, twist, twistd&
&   , chords, cl0, cla, vinf, rho, sref, srefd, cl, cd, l, ld, d, dd, &
&   loads, loadsd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL, INTENT(IN) :: gamad(n_vort), twistd(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: sref, cl, cd, l, d, loads(n_vort)
    REAL, INTENT(OUT) :: srefd, ld, dd, loadsd(n_vort)
! Working variables
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uinfd(3), aicd(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: uaid(3, n_vort), unid(3, n_vort), sid(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: areasd(n_vort), vlocald(3, n_vort), alphalocald(n_vort)
    REAL :: fcirc(3, n_vort), fbody(3), fbodym, vinfm
    REAL :: fcircd(3, n_vort), fbodyd(3), fbodymd
    INTEGER :: ii
    INTRINSIC SQRT
    REAL :: arg1
    REAL :: arg1d
    REAL :: temp
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    aicd = 0.0
    CALL GET_AIC_MATRIX_D(n_vort, x, xd, uinf, aic, aicd)
! Get geometric vectors
    areasd = 0.0
    sid = 0.0
    CALL GET_GEOM_VECTORS_D(n_vort, x, xd, twist, twistd, chords, uai, &
&                     uaid, uni, unid, si, sid, areas, areasd)
! Get induced velocities
    vlocald = 0.0
    unid = 0.0
    uaid = 0.0
    CALL GET_LOCAL_VELS_D(n_vort, gama, gamad, aic, aicd, vinf, uai, &
&                   uaid, uni, unid, vlocal, vlocald, alphalocal, &
&                   alphalocald)
! Get forces on every bound vortex
    fcircd = 0.0
    CALL COMPUTE_CIRCULATION_FORCES_D(n_vort, rho, vlocal, vlocald, si, &
&                               sid, gama, gamad, fcirc, fcircd)
! Store bending forces
    loadsd = fcircd(3, :)
    loads = fcirc(3, :)
! Get total area and forces in the system of coordinates of the body
    sref = 0.0
    fbody = 0.0
    srefd = 0.0
    fbodyd = 0.0
    DO ii=1,n_vort
      srefd = srefd + areasd(ii)
      sref = sref + areas(ii)
      fbodyd(1) = fbodyd(1) + fcircd(1, ii)
      fbody(1) = fbody(1) + fcirc(1, ii)
      fbodyd(2) = fbodyd(2) + fcircd(2, ii)
      fbody(2) = fbody(2) + fcirc(2, ii)
      fbodyd(3) = fbodyd(3) + fcircd(3, ii)
      fbody(3) = fbody(3) + fcirc(3, ii)
    END DO
! The drag is aligned with the free-stream
    uinfd = 0.0
    CALL DOT_D(fbody, fbodyd, uinf, uinfd, d, dd)
! The rest is the lift force
    CALL NORM_D(fbody, fbodyd, fbodym, fbodymd)
    arg1d = 2*fbodym*fbodymd - 2*d*dd
    arg1 = fbodym*fbodym - d*d
    temp = SQRT(arg1)
    IF (arg1 .EQ. 0.0) THEN
      ld = 0.0
    ELSE
      ld = arg1d/(2.0*temp)
    END IF
    l = temp
! Make results non dimensional
    CALL NORM(vinf, vinfm)
    cl = 2.0*l/sref/vinfm/vinfm/rho
    cd = 2.0*d/sref/vinfm/vinfm/rho
  END SUBROUTINE GET_FUNCTIONS_D0

!============================================================
  SUBROUTINE GET_FUNCTIONS(n_vort, x, gama, twist, chords, cl0, cla, &
&   vinf, rho, sref, cl, cd, l, d, loads)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: sref, cl, cd, l, d, loads(n_vort)
! Working variables
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: fcirc(3, n_vort), fbody(3), fbodym, vinfm
    INTEGER :: ii
    INTRINSIC SQRT
    REAL :: arg1
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL GET_GEOM_VECTORS(n_vort, x, twist, chords, uai, uni, si, areas)
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get forces on every bound vortex
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Store bending forces
    loads = fcirc(3, :)
! Get total area and forces in the system of coordinates of the body
    sref = 0.0
    fbody = 0.0
    DO ii=1,n_vort
      sref = sref + areas(ii)
      fbody(1) = fbody(1) + fcirc(1, ii)
      fbody(2) = fbody(2) + fcirc(2, ii)
      fbody(3) = fbody(3) + fcirc(3, ii)
    END DO
! The drag is aligned with the free-stream
    CALL DOT(fbody, uinf, d)
! The rest is the lift force
    CALL NORM(fbody, fbodym)
    arg1 = fbodym*fbodym - d*d
    l = SQRT(arg1)
! Make results non dimensional
    CALL NORM(vinf, vinfm)
    cl = 2.0*l/sref/vinfm/vinfm/rho
    cd = 2.0*d/sref/vinfm/vinfm/rho
  END SUBROUTINE GET_FUNCTIONS

!  Differentiation of norm in forward (tangent) mode:
!   variations   of useful results: am
!   with respect to varying inputs: a
!============================================================
  SUBROUTINE NORM_D(a, ad, am, amd)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(IN) :: ad(3)
    REAL, INTENT(OUT) :: am
    REAL, INTENT(OUT) :: amd
    INTRINSIC SQRT
    REAL :: arg1
    REAL :: arg1d
    REAL :: temp
    arg1d = 2*a(1)*ad(1) + 2*a(2)*ad(2) + 2*a(3)*ad(3)
    arg1 = a(1)*a(1) + a(2)*a(2) + a(3)*a(3)
    temp = SQRT(arg1)
    IF (arg1 .EQ. 0.0) THEN
      amd = 0.0
    ELSE
      amd = arg1d/(2.0*temp)
    END IF
    am = temp
  END SUBROUTINE NORM_D

!============================================================
  SUBROUTINE NORM(a, am)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(OUT) :: am
    INTRINSIC SQRT
    REAL :: arg1
    arg1 = a(1)*a(1) + a(2)*a(2) + a(3)*a(3)
    am = SQRT(arg1)
  END SUBROUTINE NORM

!  Differentiation of normalize in forward (tangent) mode:
!   variations   of useful results: an
!   with respect to varying inputs: a
!============================================================
  SUBROUTINE NORMALIZE_D(a, ad, an, and)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(IN) :: ad(3)
    REAL, INTENT(OUT) :: an(3)
    REAL, INTENT(OUT) :: and(3)
    REAL :: am
    REAL :: amd
    CALL NORM_D(a, ad, am, amd)
    and = (ad-a*amd/am)/am
    an = a/am
  END SUBROUTINE NORMALIZE_D

!============================================================
  SUBROUTINE NORMALIZE(a, an)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(OUT) :: an(3)
    REAL :: am
    CALL NORM(a, am)
    an = a/am
  END SUBROUTINE NORMALIZE

!  Differentiation of dot in forward (tangent) mode:
!   variations   of useful results: adb
!   with respect to varying inputs: a b
!============================================================
  SUBROUTINE DOT_D(a, ad, b, bd, adb, adbd)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(IN) :: ad(3), bd(3)
    REAL, INTENT(OUT) :: adb
    REAL, INTENT(OUT) :: adbd
    adbd = b(1)*ad(1) + a(1)*bd(1) + b(2)*ad(2) + a(2)*bd(2) + b(3)*ad(3&
&     ) + a(3)*bd(3)
    adb = a(1)*b(1) + a(2)*b(2) + a(3)*b(3)
  END SUBROUTINE DOT_D

!============================================================
  SUBROUTINE DOT(a, b, adb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(OUT) :: adb
    adb = a(1)*b(1) + a(2)*b(2) + a(3)*b(3)
  END SUBROUTINE DOT

!  Differentiation of cross in forward (tangent) mode:
!   variations   of useful results: acb
!   with respect to varying inputs: acb a b
!============================================================
  SUBROUTINE CROSS_D(a, ad, b, bd, acb, acbd)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(IN) :: ad(3), bd(3)
    REAL, INTENT(OUT) :: acb(3)
    REAL, INTENT(OUT) :: acbd(3)
    acbd(1) = b(3)*ad(2) + a(2)*bd(3) - b(2)*ad(3) - a(3)*bd(2)
    acb(1) = a(2)*b(3) - a(3)*b(2)
    acbd(2) = b(1)*ad(3) + a(3)*bd(1) - b(3)*ad(1) - a(1)*bd(3)
    acb(2) = a(3)*b(1) - a(1)*b(3)
    acbd(3) = b(2)*ad(1) + a(1)*bd(2) - b(1)*ad(2) - a(2)*bd(1)
    acb(3) = a(1)*b(2) - a(2)*b(1)
  END SUBROUTINE CROSS_D

!============================================================
  SUBROUTINE CROSS(a, b, acb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(OUT) :: acb(3)
    acb(1) = a(2)*b(3) - a(3)*b(2)
    acb(2) = a(3)*b(1) - a(1)*b(3)
    acb(3) = a(1)*b(2) - a(2)*b(1)
  END SUBROUTINE CROSS

!  Differentiation of llt_main in forward (tangent) mode:
!   variations   of useful results: d res loads l sref
!   with respect to varying inputs: x twist gama
!============================================================
  SUBROUTINE LLT_MAIN_D(n_vort, x, xd, gama, gamad, twist, twistd, &
&   chords, cl0, cla, vinf, rho, res, resd, sref, srefd, cl, cd, l, ld, &
&   d, dd, loads, loadsd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL, INTENT(IN) :: gamad(n_vort), twistd(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort), sref, cl, cd, l, d
    REAL, INTENT(OUT) :: resd(n_vort), srefd, ld, dd
    REAL, INTENT(OUT) :: loads(n_vort)
    REAL, INTENT(OUT) :: loadsd(n_vort)
! EXECUTION
! Call relevant subroutines
    CALL GET_RESIDUALS_D0(n_vort, x, xd, gama, gamad, twist, twistd, &
&                   chords, cl0, cla, vinf, rho, res, resd)
    CALL GET_FUNCTIONS_D0(n_vort, x, xd, gama, gamad, twist, twistd, &
&                   chords, cl0, cla, vinf, rho, sref, srefd, cl, cd, l&
&                   , ld, d, dd, loads, loadsd)
  END SUBROUTINE LLT_MAIN_D

!============================================================
  SUBROUTINE LLT_MAIN(n_vort, x, gama, twist, chords, cl0, cla, vinf, &
&   rho, res, sref, cl, cd, l, d, loads)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort), sref, cl, cd, l, d
    REAL, INTENT(OUT) :: loads(n_vort)
! EXECUTION
! Call relevant subroutines
    CALL GET_RESIDUALS(n_vort, x, gama, twist, chords, cl0, cla, vinf, &
&                rho, res)
    CALL GET_FUNCTIONS(n_vort, x, gama, twist, chords, cl0, cla, vinf, &
&                rho, sref, cl, cd, l, d, loads)
  END SUBROUTINE LLT_MAIN

END MODULE LLT_MODULE_D

