!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 20 Jun 2026 11:35
!
MODULE ASA_MODULE_B
  IMPLICIT NONE
  REAL, SAVE :: zero=0.0
  REAL, SAVE :: pi=3.1415926535897932384626
  REAL, SAVE :: eps=EPSILON(zero)

CONTAINS
!  Differentiation of transfer_disps in reverse (adjoint) mode:
!   gradient     of useful results: d xllt
!   with respect to varying inputs: d
  SUBROUTINE TRANSFER_DISPS_B(n_nodes, xfem, d, db, xllt, xlltb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_nodes
    REAL, INTENT(IN) :: xfem(3, n_nodes), d(2*n_nodes)
    REAL :: db(2*n_nodes)
! Output variables
    REAL :: xllt(3, n_nodes)
    REAL :: xlltb(3, n_nodes)
! EXECUTION
! Copy Xfem to Xllt, but just apply displacements in the z direction
    db(1:2*n_nodes:2) = db(1:2*n_nodes:2) + xlltb(3, :)
  END SUBROUTINE TRANSFER_DISPS_B

  SUBROUTINE TRANSFER_DISPS(n_nodes, xfem, d, xllt)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_nodes
    REAL, INTENT(IN) :: xfem(3, n_nodes), d(2*n_nodes)
! Output variables
    REAL, INTENT(OUT) :: xllt(3, n_nodes)
! EXECUTION
! Copy Xfem to Xllt, but just apply displacements in the z direction
    xllt(1, :) = xfem(1, :)
    xllt(2, :) = xfem(2, :)
    xllt(3, :) = xfem(3, :) + d(::2)
  END SUBROUTINE TRANSFER_DISPS

!  Differentiation of transfer_forces in reverse (adjoint) mode:
!   gradient     of useful results: f
!   with respect to varying inputs: loads
!============================================================
  SUBROUTINE TRANSFER_FORCES_B(n_nodes, xfem, loads, loadsb, f, fb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_nodes
    REAL, INTENT(IN) :: xfem(3, n_nodes), loads(n_nodes-1)
    REAL :: loadsb(n_nodes-1)
! Output variables
    REAL :: f(2*n_nodes)
    REAL :: fb(2*n_nodes)
! Working variables
    REAL :: l(n_nodes-1)
    INTEGER :: ii
! EXECUTION
! Compute the panel lengths along the span axis (y-dim)
    l = xfem(2, 2:n_nodes) - xfem(2, 1:n_nodes-1)
! Initialize consistent force vector
    loadsb = 0.0
    DO ii=n_nodes-1,1,-1
      loadsb(ii) = loadsb(ii) + fb(2*ii+1)/2 - l(ii)*fb(2*ii+2)/12 + l(&
&       ii)*fb(2*ii)/12 + fb(2*ii-1)/2
    END DO
  END SUBROUTINE TRANSFER_FORCES_B

!============================================================
  SUBROUTINE TRANSFER_FORCES(n_nodes, xfem, loads, f)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_nodes
    REAL, INTENT(IN) :: xfem(3, n_nodes), loads(n_nodes-1)
! Output variables
    REAL, INTENT(OUT) :: f(2*n_nodes)
! Working variables
    REAL :: l(n_nodes-1)
    INTEGER :: ii
! EXECUTION
! Compute the panel lengths along the span axis (y-dim)
    l = xfem(2, 2:n_nodes) - xfem(2, 1:n_nodes-1)
! Initialize consistent force vector
    f = zero
! Compute contributions of each horseshoe vortex to the consistent forces
    DO ii=1,n_nodes-1
      f(2*ii-1) = f(2*ii-1) + loads(ii)/2
      f(2*ii) = f(2*ii) + loads(ii)*l(ii)/12
      f(2*ii+1) = f(2*ii+1) + loads(ii)/2
      f(2*ii+2) = f(2*ii+2) - loads(ii)*l(ii)/12
    END DO
  END SUBROUTINE TRANSFER_FORCES

!  Differentiation of asa_main in reverse (adjoint) mode:
!   gradient     of useful results: liftexcess ksmargin resllt
!                fb margins resfem weight
!   with respect to varying inputs: liftexcess d t ksmargin twist
!                resllt fb margins resfem gama weight
!   RW status of diff variables: liftexcess:in-zero d:out t:out
!                ksmargin:in-zero twist:out resllt:in-out fb:in-zero
!                margins:in-out resfem:in-zero gama:out weight:in-zero
!============================================================
  SUBROUTINE ASA_MAIN_B(n_panels, gama, gamab, twist, twistb, chords, &
&   span, r, t, tb, d, db, cl0, cla, vinf, rhoair, e, rhomat, sigmay, &
&   pks, cd0, fixedmass, g, endurance, tsfc, loadfactor, resllt, reslltb&
&   , resfem, resfemb, liftexcess, liftexcessb, margins, marginsb, &
&   ksmargin, ksmarginb, fb, fbb, weight, weightb, sref, cl)
! This subroutine computes the residuals of the coupled aerostructural
! problem.
!
! INPUTS
!
! n_panels: integer -> Number of horseshoe panels and beams (the same).
! Gama: real(n_panels) -> Circulation intensity of each horseshoe vortex.
! twist: real(n_panels) -> Array of local incidence angles.
! chords: real(n_panels) -> Array of local chords.
! span: real -> Wing span.
! r: real(n_panels) -> Radius of each beam element.
! t: real(n_panels) -> Wall thickness of each beam element.
! d: real(2*(n_panels+1)) -> Displacements values of all DOFs (including
!                           the constrained ones).
! cl0: real(n_panels) -> cl0 of each 2D section
! cla: real(n_panels) -> lift curve slope of each 2D section [1/rad]
! Vinf: real(3) -> Free-stream velocity vector
! rhoAir: real -> Air density
! E: real -> Young's module of the beam material.
! rhoMat: real -> Density of the beam material.
! sigmaY: real -> Yield stress of the beam material.
! pKS: real -> Constant of the KS functons used to aggregate stresses.
! CD0: real -> Parasite drag that will be added to the induced drag.
! fixedMass: real -> Fixed mass of the aircraft less the wing structure.
! g: real -> Acceleration of gravity.
! Endurance: real -> Desired endurance of the aircraft.
! TSFC: real -> Thrust specific fuel consumption of the engine.
! loadFactor: real -> Factor applied to the structural failure margin
!                     to consider a multiplicative factor in the loads.
!
! OUTPUTS
!
! resllt: real(n_panels) -> Residuals of the LLT method
! resfem: real(2*(n_panels+1)) -> Residuals of the FEM model
!                                 considering all DOFs (including the
!                                 constrained ones). The residuals
!                                 of the constrained DOFs are the
!                                 displacements themselves, so that the
!                                 solver drives them to zero. We
!                                 modify the K matrix in appy_cons to
!                                 achieve that.
! liftExcess: real -> Difference between the generated lift and the.
!                     aircraft weight. This value is normalized:
!                     liftExcess = Lift/Weigth - 1
! margins: real(2*n_panels) -> Margin from Von Mises stress at each node
!                              with respect to the yield stress.
!                              The margins are computed as:
!                              margin = 1.0 - sigma_vm/sigmaY
!                              Negative margins indicate failure.
!                              Internal nodes have two values
!                              corresponding to the beam sections on
!                              either side. KSmargin is the aggregation of
!                              these values.
! KSmargin: real -> Aggregated safety margin. This value
!                   is a conservative estimate of the minimum
!                   margin value in the structure. This estimate
!                   gets closer to the real value as we increase
!                   pKS, but this may lead to numerical issues.
! FB: real -> Fuel burn (in Force units).
! Weight: real -> Total weight of the aircraft (in Force units)
!                 (fixed weight + structure weight + fuel weight)
! Sref: real -> Area of all panels
! CL: real -> Lift coefficient (adimensionalized by Sref)
    USE LLT_MODULE_B, ONLY : llt_main, llt_main_b
    USE FEM_MODULE_B, ONLY : fem_main, fem_main_b
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_panels
    REAL, INTENT(IN) :: gama(n_panels), twist(n_panels)
    REAL :: gamab(n_panels), twistb(n_panels)
    REAL, INTENT(IN) :: chords(n_panels)
    REAL, INTENT(IN) :: span
    REAL, INTENT(IN) :: r(n_panels), t(n_panels)
    REAL :: tb(n_panels)
    REAL, INTENT(IN) :: d(2*(n_panels+1))
    REAL :: db(2*(n_panels+1))
    REAL, INTENT(IN) :: cl0(n_panels), cla(n_panels), vinf(3), rhoair
    REAL, INTENT(IN) :: e, rhomat, sigmay, pks
    REAL, INTENT(IN) :: cd0, fixedmass, g, endurance, tsfc, loadfactor
! Output variables
    REAL :: resllt(n_panels), resfem(2*(n_panels+1))
    REAL :: reslltb(n_panels), resfemb(2*(n_panels+1))
    REAL :: liftexcess, margins(2*n_panels)
    REAL :: liftexcessb, marginsb(2*n_panels)
    REAL :: ksmargin, fb, weight, sref, cl
    REAL :: ksmarginb, fbb, weightb, srefb
! Working variables
    REAL :: xfem(3, n_panels+1)
    REAL :: xllt(3, n_panels+1), cd, lift, drag
    REAL :: xlltb(3, n_panels+1), liftb, dragb
    REAL :: loads(n_panels), f(2*(n_panels+1)), structmass
    REAL :: loadsb(n_panels), fb0(2*(n_panels+1)), structmassb
    REAL :: vinfm2
    INTEGER :: n_cons, conids(2)
    INTEGER :: ii, n_nodes
    INTRINSIC REAL
    INTRINSIC EXP
    REAL :: temp
    REAL :: tempb
! EXECUTION
! Identify the indices of the structural DOFs that should
! be constrained, which corresponds to the central node.
! The first node of the wing has degrees of freedom 1 and 2,
! the second node has degrees of freedom 3 and 4, and so on.
! If we have n_panels elements, the degrees of freedom of the
! central node will be n_panels+1 and n_panels+2.
    n_cons = 2
    conids(1) = n_panels + 1
    conids(2) = n_panels + 2
    n_nodes = n_panels + 1
! ==================
! ADD YOUR CODE HERE
! ==================
! ==================
! STEP 1: Build the FEM nodes coordinates 
! ==================
    DO ii=1,n_nodes
      xfem(1, ii) = 0.0
      xfem(2, ii) = -(span/2.0) + (ii-1)*span/REAL(n_panels)
      xfem(3, ii) = 0.0
    END DO
! ==================
! STEP 2: Call modules
! ==================
! Transfer the displacements from the FEM model to the LLT model
    CALL TRANSFER_DISPS(n_nodes, xfem, d, xllt)
! Call the LLT solver to compute the aerodynamic loads
! input variables
! output variables
    CALL LLT_MAIN(n_panels, xllt, gama, twist, chords, cl0, cla, vinf, &
&           rhoair, resllt, sref, cl, cd, lift, drag, loads)
! Transfer the aerodynamic loads from the LLT model to the FEM model
    CALL TRANSFER_FORCES(n_nodes, xfem, loads, f)
! Call the FEM solver to compute the structural response
! input variables
! output variables
    CALL PUSHREAL8ARRAY(margins, 2*n_panels)
    CALL FEM_MAIN(n_panels, n_cons, xfem, r, t, f, d, e, rhomat, sigmay&
&           , pks, conids, resfem, structmass, margins, ksmargin)
! ==================
! STEP 3: Convert margins by the loadfactor
! ==================
! ==================
! STEP 4: Convert KSmargins by the loadfactor
! ==================
! ==================
! STEP 5: Compute magnitude of Vinf
! ==================
    vinfm2 = vinf(1)**2 + vinf(2)**2 + vinf(3)**2
! ==================
! STEP 6: Compute total drag of the wing
! ==================
    drag = drag + rhoair*vinfm2*cd0*sref/2.0
! ==================
! STEP 7: Compute Fuel Burn
! ==================
    fb = (structmass+fixedmass)*g*(EXP(endurance*tsfc/(lift/drag))-1)
! ==================
! STEP 8: Compute Total weight
! ==================
    weight = (structmass+fixedmass)*g + fb
! ==================
! STEP 9: Compute Lift excess
! ==================
    weightb = weightb - lift*liftexcessb/weight**2
    fbb = fbb + weightb
    temp = endurance*tsfc*drag/lift
    tempb = endurance*tsfc*EXP(temp)*(fixedmass+structmass)*g*fbb/lift
    liftb = liftexcessb/weight - drag*tempb/lift
    structmassb = g*weightb + (EXP(temp)-1)*g*fbb
    dragb = tempb
    srefb = rhoair*vinfm2*cd0*dragb/2.0
    ksmarginb = loadfactor*ksmarginb
    marginsb = loadfactor*marginsb
    CALL POPREAL8ARRAY(margins, 2*n_panels)
    db = 0.0
    tb = 0.0
    fb0 = 0.0
    CALL FEM_MAIN_B(n_panels, n_cons, xfem, r, t, tb, f, fb0, d, db, e, &
&             rhomat, sigmay, pks, conids, resfem, resfemb, structmass, &
&             structmassb, margins, marginsb, ksmargin, ksmarginb)
    loadsb = 0.0
    CALL TRANSFER_FORCES_B(n_nodes, xfem, loads, loadsb, f, fb0)
    twistb = 0.0
    gamab = 0.0
    xlltb = 0.0
    CALL LLT_MAIN_B(n_panels, xllt, xlltb, gama, gamab, twist, twistb, &
&             chords, cl0, cla, vinf, rhoair, resllt, reslltb, sref, &
&             srefb, cl, cd, lift, liftb, drag, dragb, loads, loadsb)
    CALL TRANSFER_DISPS_B(n_nodes, xfem, d, db, xllt, xlltb)
    liftexcessb = 0.0
    ksmarginb = 0.0
    fbb = 0.0
    resfemb = 0.0
    weightb = 0.0
  END SUBROUTINE ASA_MAIN_B

!============================================================
  SUBROUTINE ASA_MAIN(n_panels, gama, twist, chords, span, r, t, d, cl0&
&   , cla, vinf, rhoair, e, rhomat, sigmay, pks, cd0, fixedmass, g, &
&   endurance, tsfc, loadfactor, resllt, resfem, liftexcess, margins, &
&   ksmargin, fb, weight, sref, cl)
! This subroutine computes the residuals of the coupled aerostructural
! problem.
!
! INPUTS
!
! n_panels: integer -> Number of horseshoe panels and beams (the same).
! Gama: real(n_panels) -> Circulation intensity of each horseshoe vortex.
! twist: real(n_panels) -> Array of local incidence angles.
! chords: real(n_panels) -> Array of local chords.
! span: real -> Wing span.
! r: real(n_panels) -> Radius of each beam element.
! t: real(n_panels) -> Wall thickness of each beam element.
! d: real(2*(n_panels+1)) -> Displacements values of all DOFs (including
!                           the constrained ones).
! cl0: real(n_panels) -> cl0 of each 2D section
! cla: real(n_panels) -> lift curve slope of each 2D section [1/rad]
! Vinf: real(3) -> Free-stream velocity vector
! rhoAir: real -> Air density
! E: real -> Young's module of the beam material.
! rhoMat: real -> Density of the beam material.
! sigmaY: real -> Yield stress of the beam material.
! pKS: real -> Constant of the KS functons used to aggregate stresses.
! CD0: real -> Parasite drag that will be added to the induced drag.
! fixedMass: real -> Fixed mass of the aircraft less the wing structure.
! g: real -> Acceleration of gravity.
! Endurance: real -> Desired endurance of the aircraft.
! TSFC: real -> Thrust specific fuel consumption of the engine.
! loadFactor: real -> Factor applied to the structural failure margin
!                     to consider a multiplicative factor in the loads.
!
! OUTPUTS
!
! resllt: real(n_panels) -> Residuals of the LLT method
! resfem: real(2*(n_panels+1)) -> Residuals of the FEM model
!                                 considering all DOFs (including the
!                                 constrained ones). The residuals
!                                 of the constrained DOFs are the
!                                 displacements themselves, so that the
!                                 solver drives them to zero. We
!                                 modify the K matrix in appy_cons to
!                                 achieve that.
! liftExcess: real -> Difference between the generated lift and the.
!                     aircraft weight. This value is normalized:
!                     liftExcess = Lift/Weigth - 1
! margins: real(2*n_panels) -> Margin from Von Mises stress at each node
!                              with respect to the yield stress.
!                              The margins are computed as:
!                              margin = 1.0 - sigma_vm/sigmaY
!                              Negative margins indicate failure.
!                              Internal nodes have two values
!                              corresponding to the beam sections on
!                              either side. KSmargin is the aggregation of
!                              these values.
! KSmargin: real -> Aggregated safety margin. This value
!                   is a conservative estimate of the minimum
!                   margin value in the structure. This estimate
!                   gets closer to the real value as we increase
!                   pKS, but this may lead to numerical issues.
! FB: real -> Fuel burn (in Force units).
! Weight: real -> Total weight of the aircraft (in Force units)
!                 (fixed weight + structure weight + fuel weight)
! Sref: real -> Area of all panels
! CL: real -> Lift coefficient (adimensionalized by Sref)
    USE LLT_MODULE_B, ONLY : llt_main
    USE FEM_MODULE_B, ONLY : fem_main
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_panels
    REAL, INTENT(IN) :: gama(n_panels), twist(n_panels)
    REAL, INTENT(IN) :: chords(n_panels)
    REAL, INTENT(IN) :: span
    REAL, INTENT(IN) :: r(n_panels), t(n_panels)
    REAL, INTENT(IN) :: d(2*(n_panels+1))
    REAL, INTENT(IN) :: cl0(n_panels), cla(n_panels), vinf(3), rhoair
    REAL, INTENT(IN) :: e, rhomat, sigmay, pks
    REAL, INTENT(IN) :: cd0, fixedmass, g, endurance, tsfc, loadfactor
! Output variables
    REAL, INTENT(OUT) :: resllt(n_panels), resfem(2*(n_panels+1))
    REAL, INTENT(OUT) :: liftexcess, margins(2*n_panels)
    REAL, INTENT(OUT) :: ksmargin, fb, weight, sref, cl
! Working variables
    REAL :: xfem(3, n_panels+1)
    REAL :: xllt(3, n_panels+1), cd, lift, drag
    REAL :: loads(n_panels), f(2*(n_panels+1)), structmass
    REAL :: vinfm2
    INTEGER :: n_cons, conids(2)
    INTEGER :: ii, n_nodes
    INTRINSIC REAL
    INTRINSIC EXP
! EXECUTION
! Identify the indices of the structural DOFs that should
! be constrained, which corresponds to the central node.
! The first node of the wing has degrees of freedom 1 and 2,
! the second node has degrees of freedom 3 and 4, and so on.
! If we have n_panels elements, the degrees of freedom of the
! central node will be n_panels+1 and n_panels+2.
    n_cons = 2
    conids(1) = n_panels + 1
    conids(2) = n_panels + 2
    n_nodes = n_panels + 1
! ==================
! ADD YOUR CODE HERE
! ==================
! ==================
! STEP 1: Build the FEM nodes coordinates 
! ==================
    DO ii=1,n_nodes
      xfem(1, ii) = 0.0
      xfem(2, ii) = -(span/2.0) + (ii-1)*span/REAL(n_panels)
      xfem(3, ii) = 0.0
    END DO
! ==================
! STEP 2: Call modules
! ==================
! Transfer the displacements from the FEM model to the LLT model
    CALL TRANSFER_DISPS(n_nodes, xfem, d, xllt)
! Call the LLT solver to compute the aerodynamic loads
! input variables
! output variables
    CALL LLT_MAIN(n_panels, xllt, gama, twist, chords, cl0, cla, vinf, &
&           rhoair, resllt, sref, cl, cd, lift, drag, loads)
! Transfer the aerodynamic loads from the LLT model to the FEM model
    CALL TRANSFER_FORCES(n_nodes, xfem, loads, f)
! Call the FEM solver to compute the structural response
! input variables
! output variables
    CALL FEM_MAIN(n_panels, n_cons, xfem, r, t, f, d, e, rhomat, sigmay&
&           , pks, conids, resfem, structmass, margins, ksmargin)
! ==================
! STEP 3: Convert margins by the loadfactor
! ==================
    margins = loadfactor*margins + 1 - loadfactor
! ==================
! STEP 4: Convert KSmargins by the loadfactor
! ==================
    ksmargin = loadfactor*ksmargin + 1 - loadfactor
! ==================
! STEP 5: Compute magnitude of Vinf
! ==================
    vinfm2 = vinf(1)**2 + vinf(2)**2 + vinf(3)**2
! ==================
! STEP 6: Compute total drag of the wing
! ==================
    drag = drag + rhoair*vinfm2*cd0*sref/2.0
! ==================
! STEP 7: Compute Fuel Burn
! ==================
    fb = (structmass+fixedmass)*g*(EXP(endurance*tsfc/(lift/drag))-1)
! ==================
! STEP 8: Compute Total weight
! ==================
    weight = (structmass+fixedmass)*g + fb
! ==================
! STEP 9: Compute Lift excess
! ==================
    liftexcess = lift/weight - 1
  END SUBROUTINE ASA_MAIN

END MODULE ASA_MODULE_B

