!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 24 Mar 2026 19:29
!
MODULE LLT_MODULE_B
  IMPLICIT NONE
  REAL, SAVE :: zero=0.0
  REAL, SAVE :: pi=3.1415926535897932384626
  REAL, SAVE :: eps=EPSILON(zero)

CONTAINS
!  Differentiation of induced_vel in reverse (adjoint) mode:
!   gradient     of useful results: xp gamma_ind
!   with respect to varying inputs: xp x1 x2
  SUBROUTINE INDUCED_VEL_B(uinf, x1, x1b, x2, x2b, xp, xpb, gamma_ind, &
&   gamma_indb)
    IMPLICIT NONE
! Input variables
    REAL, INTENT(IN) :: uinf(3), x1(3), x2(3), xp(3)
    REAL :: x1b(3), x2b(3), xpb(3)
! Output variables
    REAL :: gamma_ind(3)
    REAL :: gamma_indb(3)
! Working variables
    REAL :: r1(3), r2(3), v1(3), v2(3), v3(3)
    REAL :: r1b(3), r2b(3), v1b(3), v2b(3), v3b(3)
    REAL :: uinfcr1(3), uinfcr2(3), r1cr2(3)
    REAL :: uinfcr1b(3), uinfcr2b(3), r1cr2b(3)
    REAL :: r1m, r2m, uinfdr1, uinfdr2, r1dr2, den
    REAL :: r1mb, r2mb, uinfdr1b, uinfdr2b, r1dr2b, denb
    INTRINSIC ABS
    REAL :: abs0
    REAL, DIMENSION(3) :: uinfb
    REAL :: temp
    REAL :: tempb
    REAL, DIMENSION(3) :: tempb0
    REAL :: temp0
    REAL :: tempb1
    INTEGER*4 :: branch
! EXECUTION
! Compute vectors between the kinks and the point of interest
    r1 = xp - x1
    r2 = xp - x2
! Compute the magnitude of these vectors
    CALL NORM(r1, r1m)
    CALL NORM(r2, r2m)
! Compute cross products
    CALL CROSS(uinf, r1, uinfcr1)
    CALL CROSS(uinf, r2, uinfcr2)
    CALL CROSS(r1, r2, r1cr2)
! Compute dot products
    CALL DOT(uinf, r1, uinfdr1)
    CALL DOT(uinf, r2, uinfdr2)
    CALL DOT(r1, r2, r1dr2)
! Compute contributions of each vortex segment
    den = r1m*r2m + r1dr2
    IF (den .GE. 0.) THEN
      abs0 = den
    ELSE
      abs0 = -den
    END IF
    IF (abs0 .GT. eps) THEN
      CALL PUSHCONTROL1B(0)
    ELSE
      CALL PUSHCONTROL1B(1)
    END IF
    v1b = 0.0
    v2b = 0.0
    v3b = 0.0
    tempb0 = 0.25*gamma_indb/pi
    v1b = tempb0
    v2b = tempb0
    v3b = tempb0
    uinfcr1b = 0.0
    temp0 = r1m*(r1m-uinfdr1)
    uinfcr1b = -(v3b/temp0)
    tempb1 = SUM(uinfcr1*v3b)/temp0**2
    r1mb = (2*r1m-uinfdr1)*tempb1
    uinfdr1b = -(r1m*tempb1)
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      r1cr2b = 0.0
      temp = r1m*r2m*den
      tempb0 = v2b/temp
      tempb1 = SUM(r1cr2*tempb0)
      r1cr2b = (r1m+r2m)*tempb0
      tempb = -(SUM(r1cr2*tempb0)*(r1m+r2m)/temp)
      r1mb = r1mb + r2m*den*tempb + tempb1
      r2mb = r1m*den*tempb + tempb1
      denb = r1m*r2m*tempb
    ELSE
      r2mb = 0.0
      denb = 0.0
      r1cr2b = 0.0
    END IF
    temp = r2m*(r2m-uinfdr2)
    tempb = -(SUM(uinfcr2*v1b)/temp**2)
    r1mb = r1mb + r2m*denb
    r2mb = r2mb + r1m*denb + (2*r2m-uinfdr2)*tempb
    r1dr2b = denb
    uinfcr2b = 0.0
    uinfcr2b = v1b/temp
    uinfdr2b = -(r2m*tempb)
    r1b = 0.0
    r2b = 0.0
    CALL DOT_B(r1, r1b, r2, r2b, r1dr2, r1dr2b)
    uinfb = 0.0
    CALL DOT_B(uinf, uinfb, r2, r2b, uinfdr2, uinfdr2b)
    uinfb = 0.0
    CALL DOT_B(uinf, uinfb, r1, r1b, uinfdr1, uinfdr1b)
    CALL CROSS_B(r1, r1b, r2, r2b, r1cr2, r1cr2b)
    uinfb = 0.0
    CALL CROSS_B(uinf, uinfb, r2, r2b, uinfcr2, uinfcr2b)
    uinfb = 0.0
    CALL CROSS_B(uinf, uinfb, r1, r1b, uinfcr1, uinfcr1b)
    CALL NORM_B(r2, r2b, r2m, r2mb)
    CALL NORM_B(r1, r1b, r1m, r1mb)
    x2b = 0.0
    xpb = xpb + r2b + r1b
    x2b = -r2b
    x1b = 0.0
    x1b = -r1b
  END SUBROUTINE INDUCED_VEL_B

  SUBROUTINE INDUCED_VEL(uinf, x1, x2, xp, gamma_ind)
    IMPLICIT NONE
! Input variables
    REAL, INTENT(IN) :: uinf(3), x1(3), x2(3), xp(3)
! Output variables
    REAL, INTENT(OUT) :: gamma_ind(3)
! Working variables
    REAL :: r1(3), r2(3), v1(3), v2(3), v3(3)
    REAL :: uinfcr1(3), uinfcr2(3), r1cr2(3)
    REAL :: r1m, r2m, uinfdr1, uinfdr2, r1dr2, den
    INTRINSIC ABS
    REAL :: abs0
! EXECUTION
! Compute vectors between the kinks and the point of interest
    r1 = xp - x1
    r2 = xp - x2
! Compute the magnitude of these vectors
    CALL NORM(r1, r1m)
    CALL NORM(r2, r2m)
! Compute cross products
    CALL CROSS(uinf, r1, uinfcr1)
    CALL CROSS(uinf, r2, uinfcr2)
    CALL CROSS(r1, r2, r1cr2)
! Compute dot products
    CALL DOT(uinf, r1, uinfdr1)
    CALL DOT(uinf, r2, uinfdr2)
    CALL DOT(r1, r2, r1dr2)
! Compute contributions of each vortex segment
    v1 = uinfcr2/r2m/(r2m-uinfdr2)
    den = r1m*r2m + r1dr2
    IF (den .GE. 0.) THEN
      abs0 = den
    ELSE
      abs0 = -den
    END IF
    IF (abs0 .GT. eps) THEN
      v2 = (r1m+r2m)*r1cr2/r1m/r2m/den
    ELSE
! Bound vortex induces no velocity along its length
      v2 = zero
    END IF
    v3 = -(uinfcr1/r1m/(r1m-uinfdr1))
! Compute overall induced velocity (without the circulation: V/gamma)
    gamma_ind = 0.25*(v1+v2+v3)/pi
  END SUBROUTINE INDUCED_VEL

!  Differentiation of get_aic_matrix in reverse (adjoint) mode:
!   gradient     of useful results: x aic
!   with respect to varying inputs: x
!============================================================
  SUBROUTINE GET_AIC_MATRIX_B(n_vort, x, xb, uinf, aic, aicb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: uinf(3)
! Output variables
    REAL :: aic(3, n_vort, n_vort)
    REAL :: aicb(3, n_vort, n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: x1(3), x2(3), xcen(3), gamma_ind(3)
    REAL :: x1b(3), x2b(3), xcenb(3), gamma_indb(3)
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1 = x(:, ii)
      x2 = x(:, ii+1)
! Compute the center of the bound vortex
      CALL PUSHREAL8ARRAY(xcen, 3)
      xcen = 0.5*(x1+x2)
    END DO
    DO ii=n_vort,1,-1
      xcenb = 0.0
      DO jj=n_vort,1,-1
        gamma_indb = 0.0
        gamma_indb = aicb(:, jj, ii)
        aicb(:, jj, ii) = 0.0
        x1 = x(:, jj)
        x2 = x(:, jj+1)
        CALL INDUCED_VEL_B(uinf, x1, x1b, x2, x2b, xcen, xcenb, &
&                    gamma_ind, gamma_indb)
        xb(:, jj+1) = xb(:, jj+1) + x2b
        xb(:, jj) = xb(:, jj) + x1b
      END DO
      x1b = 0.0
      x2b = 0.0
      CALL POPREAL8ARRAY(xcen, 3)
      x1b = 0.5*xcenb
      x2b = 0.5*xcenb
      xb(:, ii+1) = xb(:, ii+1) + x2b
      xb(:, ii) = xb(:, ii) + x1b
    END DO
  END SUBROUTINE GET_AIC_MATRIX_B

!============================================================
  SUBROUTINE GET_AIC_MATRIX(n_vort, x, uinf, aic)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: uinf(3)
! Output variables
    REAL, INTENT(OUT) :: aic(3, n_vort, n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: x1(3), x2(3), xcen(3), gamma_ind(3)
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1 = x(:, ii)
      x2 = x(:, ii+1)
! Compute the center of the bound vortex
      xcen = 0.5*(x1+x2)
! Loop over all bound vortices to compute the influence coefficients
      DO jj=1,n_vort
! Get kink coordinates of the current vortex
        x1 = x(:, jj)
        x2 = x(:, jj+1)
! The induced velocity, normalized by gamma, is the influence
! coefficient.
        CALL INDUCED_VEL(uinf, x1, x2, xcen, gamma_ind)
        aic(:, jj, ii) = gamma_ind
      END DO
    END DO
  END SUBROUTINE GET_AIC_MATRIX

!  Differentiation of get_geom_vectors in reverse (adjoint) mode:
!   gradient     of useful results: x uai twist uni si areas
!   with respect to varying inputs: x twist
!============================================================
  SUBROUTINE GET_GEOM_VECTORS_B(n_vort, x, xb, twist, twistb, chords, &
&   uai, uaib, uni, unib, si, sib, areas, areasb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: twist(n_vort), chords(n_vort)
    REAL :: twistb(n_vort)
! Output variables
    REAL :: uai(3, n_vort), uni(3, n_vort)
    REAL :: uaib(3, n_vort), unib(3, n_vort)
    REAL :: si(3, n_vort), areas(n_vort)
    REAL :: sib(3, n_vort), areasb(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: x1(3), x2(3), usi(3), ni(3)
    REAL :: x1b(3), x2b(3), usib(3), nib(3)
    REAL :: nim, sim
    REAL :: nimb, simb
    INTRINSIC COS
    INTRINSIC SIN
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1 = x(:, ii)
      x2 = x(:, ii+1)
! Compute the vector along the local span
      si(:, ii) = x2 - x1
      CALL PUSHREAL8ARRAY(usi, 3)
      CALL NORMALIZE(si(:, ii), usi)
! Create a unitary vector along the chordline
! pointing to the trailing edge
      uai(1, ii) = COS(twist(ii))
      uai(2, ii) = zero
      uai(3, ii) = -SIN(twist(ii))
! Get the normal vector as the normal between the span
! and the chord vector
      CALL PUSHREAL8ARRAY(ni, 3)
      CALL CROSS(uai(:, ii), usi, ni)
! Compute the local area of the panel.
! The norm of the normal vector is the sine of the angle.
      CALL PUSHREAL8(nim)
      CALL NORM(ni, nim)
      CALL PUSHREAL8(sim)
      CALL NORM(si(:, ii), sim)
    END DO
    nib = 0.0
    DO ii=n_vort,1,-1
      nimb = sim*chords(ii)*areasb(ii)
      simb = nim*chords(ii)*areasb(ii)
      areasb(ii) = 0.0
      CALL POPREAL8(sim)
      CALL NORM_B(si(:, ii), sib(:, ii), sim, simb)
      CALL POPREAL8(nim)
      CALL NORM_B(ni, nib, nim, nimb)
      CALL NORMALIZE_B(ni, nib, uni(:, ii), unib(:, ii))
      unib(:, ii) = 0.0
      CALL POPREAL8ARRAY(ni, 3)
      usib = 0.0
      CALL CROSS_B(uai(:, ii), uaib(:, ii), usi, usib, ni, nib)
      twistb(ii) = twistb(ii) - COS(twist(ii))*uaib(3, ii) - SIN(twist(&
&       ii))*uaib(1, ii)
      uaib(3, ii) = 0.0
      uaib(2, ii) = 0.0
      uaib(1, ii) = 0.0
      CALL POPREAL8ARRAY(usi, 3)
      CALL NORMALIZE_B(si(:, ii), sib(:, ii), usi, usib)
      x1b = 0.0
      x2b = 0.0
      x2b = sib(:, ii)
      x1b = -sib(:, ii)
      sib(:, ii) = 0.0
      xb(:, ii+1) = xb(:, ii+1) + x2b
      xb(:, ii) = xb(:, ii) + x1b
    END DO
  END SUBROUTINE GET_GEOM_VECTORS_B

!============================================================
  SUBROUTINE GET_GEOM_VECTORS(n_vort, x, twist, chords, uai, uni, si, &
&   areas)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: twist(n_vort), chords(n_vort)
! Output variables
    REAL, INTENT(OUT) :: uai(3, n_vort), uni(3, n_vort)
    REAL, INTENT(OUT) :: si(3, n_vort), areas(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: x1(3), x2(3), usi(3), ni(3)
    REAL :: nim, sim
    INTRINSIC COS
    INTRINSIC SIN
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1 = x(:, ii)
      x2 = x(:, ii+1)
! Compute the vector along the local span
      si(:, ii) = x2 - x1
      CALL NORMALIZE(si(:, ii), usi)
! Create a unitary vector along the chordline
! pointing to the trailing edge
      uai(1, ii) = COS(twist(ii))
      uai(2, ii) = zero
      uai(3, ii) = -SIN(twist(ii))
! Get the normal vector as the normal between the span
! and the chord vector
      CALL CROSS(uai(:, ii), usi, ni)
      CALL NORMALIZE(ni, uni(:, ii))
! Compute the local area of the panel.
! The norm of the normal vector is the sine of the angle.
      CALL NORM(ni, nim)
      CALL NORM(si(:, ii), sim)
      areas(ii) = nim*chords(ii)*sim
    END DO
  END SUBROUTINE GET_GEOM_VECTORS

!  Differentiation of get_local_vels in reverse (adjoint) mode:
!   gradient     of useful results: vlocal gama alphalocal
!   with respect to varying inputs: uai uni gama aic
!============================================================
  SUBROUTINE GET_LOCAL_VELS_B(n_vort, gama, gamab, aic, aicb, vinf, uai&
&   , uaib, uni, unib, vlocal, vlocalb, alphalocal, alphalocalb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: gama(n_vort), aic(3, n_vort, n_vort)
    REAL :: gamab(n_vort), aicb(3, n_vort, n_vort)
    REAL, INTENT(IN) :: vinf(3), uai(3, n_vort), uni(3, n_vort)
    REAL :: uaib(3, n_vort), unib(3, n_vort)
! Output variables
    REAL :: vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: vlocalb(3, n_vort), alphalocalb(n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: num, den
    REAL :: numb, denb
    INTRINSIC ATAN
    REAL :: tempb
! EXECUTION
! Do the matrix operation
    DO ii=1,n_vort
! Start with the free-strem contribution
      vlocal(:, ii) = vinf
! Now add the velocities induced by each vortex
      DO jj=1,n_vort
        vlocal(:, ii) = vlocal(:, ii) + aic(:, jj, ii)*gama(jj)
      END DO
! Compute the local angle of attack
      CALL PUSHREAL8(num)
      CALL DOT(vlocal(:, ii), uni(:, ii), num)
      CALL PUSHREAL8(den)
      CALL DOT(vlocal(:, ii), uai(:, ii), den)
    END DO
    uaib = 0.0
    unib = 0.0
    aicb = 0.0
    DO ii=n_vort,1,-1
      tempb = alphalocalb(ii)/(den*(1.0+(num/den)**2))
      alphalocalb(ii) = 0.0
      numb = tempb
      denb = -(num*tempb/den)
      CALL POPREAL8(den)
      CALL DOT_B(vlocal(:, ii), vlocalb(:, ii), uai(:, ii), uaib(:, ii)&
&          , den, denb)
      CALL POPREAL8(num)
      CALL DOT_B(vlocal(:, ii), vlocalb(:, ii), uni(:, ii), unib(:, ii)&
&          , num, numb)
      DO jj=n_vort,1,-1
        aicb(:, jj, ii) = aicb(:, jj, ii) + gama(jj)*vlocalb(:, ii)
        gamab(jj) = gamab(jj) + SUM(aic(:, jj, ii)*vlocalb(:, ii))
      END DO
      vlocalb(:, ii) = 0.0
    END DO
  END SUBROUTINE GET_LOCAL_VELS_B

!============================================================
  SUBROUTINE GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&   alphalocal)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: gama(n_vort), aic(3, n_vort, n_vort)
    REAL, INTENT(IN) :: vinf(3), uai(3, n_vort), uni(3, n_vort)
! Output variables
    REAL, INTENT(OUT) :: vlocal(3, n_vort), alphalocal(n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: num, den
    INTRINSIC ATAN
! EXECUTION
! Do the matrix operation
    DO ii=1,n_vort
! Start with the free-strem contribution
      vlocal(:, ii) = vinf
! Now add the velocities induced by each vortex
      DO jj=1,n_vort
        vlocal(:, ii) = vlocal(:, ii) + aic(:, jj, ii)*gama(jj)
      END DO
! Compute the local angle of attack
      CALL DOT(vlocal(:, ii), uni(:, ii), num)
      CALL DOT(vlocal(:, ii), uai(:, ii), den)
      alphalocal(ii) = ATAN(num/den)
    END DO
  END SUBROUTINE GET_LOCAL_VELS

!  Differentiation of compute_circulation_forces in reverse (adjoint) mode:
!   gradient     of useful results: vlocal gama si fcirc
!   with respect to varying inputs: vlocal gama si
!============================================================
  SUBROUTINE COMPUTE_CIRCULATION_FORCES_B(n_vort, rho, vlocal, vlocalb, &
&   si, sib, gama, gamab, fcirc, fcircb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, vlocal(3, n_vort), si(3, n_vort)
    REAL :: vlocalb(3, n_vort), sib(3, n_vort)
    REAL, INTENT(IN) :: gama(n_vort)
    REAL :: gamab(n_vort)
! Output variables
    REAL :: fcirc(3, n_vort)
    REAL :: fcircb(3, n_vort)
! Working variables
    INTEGER :: ii
    REAL :: li(3)
    REAL :: lib(3)
! EXECUTION
    DO ii=1,n_vort
! L=rho*V*gamma*l
      CALL PUSHREAL8ARRAY(li, 3)
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
    END DO
    lib = 0.0
    DO ii=n_vort,1,-1
      gamab(ii) = gamab(ii) + SUM(li*fcircb(:, ii))*rho
      lib = lib + gama(ii)*rho*fcircb(:, ii)
      fcircb(:, ii) = 0.0
      CALL POPREAL8ARRAY(li, 3)
      CALL CROSS_B(vlocal(:, ii), vlocalb(:, ii), si(:, ii), sib(:, ii)&
&            , li, lib)
    END DO
  END SUBROUTINE COMPUTE_CIRCULATION_FORCES_B

!============================================================
  SUBROUTINE COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, &
&   fcirc)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, vlocal(3, n_vort), si(3, n_vort)
    REAL, INTENT(IN) :: gama(n_vort)
! Output variables
    REAL, INTENT(OUT) :: fcirc(3, n_vort)
! Working variables
    INTEGER :: ii
    REAL :: li(3)
! EXECUTION
    DO ii=1,n_vort
! L=rho*V*gamma*l
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
      fcirc(:, ii) = rho*gama(ii)*li
    END DO
  END SUBROUTINE COMPUTE_CIRCULATION_FORCES

!  Differentiation of compute_airfoil_forces in reverse (adjoint) mode:
!   gradient     of useful results: fairf
!   with respect to varying inputs: vlocal si areas alphalocal
!============================================================
  SUBROUTINE COMPUTE_AIRFOIL_FORCES_B(n_vort, rho, cl0, cla, areas, &
&   areasb, vlocal, vlocalb, alphalocal, alphalocalb, si, sib, fairf, &
&   fairfb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, cl0(n_vort), cla(n_vort), areas(n_vort)
    REAL :: areasb(n_vort)
    REAL, INTENT(IN) :: vlocal(3, n_vort), alphalocal(n_vort), si(3, &
&   n_vort)
    REAL :: vlocalb(3, n_vort), alphalocalb(n_vort), sib(3, n_vort)
! Output variables
    REAL :: fairf(3, n_vort)
    REAL :: fairfb(3, n_vort)
! Working variables
    REAL :: fairfm, cl, li(3), uli(3), vlocalm
    REAL :: fairfmb, clb, lib(3), ulib(3), vlocalmb
    INTEGER :: ii
    REAL :: tempb
    REAL :: tempb0
! EXECUTION
! Loop over all horseshoe vortices
    DO ii=1,n_vort
! Compute the magnitude of the force given by the 2D section
! L = 0.5*Vlocal²*area*cl
      CALL PUSHREAL8(vlocalm)
      CALL NORM(vlocal(:, ii), vlocalm)
! Get normalized lift direction
      CALL PUSHREAL8ARRAY(li, 3)
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
      CALL PUSHREAL8ARRAY(uli, 3)
      CALL NORMALIZE(li, uli)
! Store the force
    END DO
    vlocalb = 0.0
    sib = 0.0
    areasb = 0.0
    alphalocalb = 0.0
    lib = 0.0
    DO ii=n_vort,1,-1
      cl = cl0(ii) + alphalocal(ii)*cla(ii)
      fairfm = 0.5*rho*vlocalm*vlocalm*areas(ii)*cl
      ulib = 0.0
      fairfmb = SUM(uli*fairfb(:, ii))
      ulib = fairfm*fairfb(:, ii)
      fairfb(:, ii) = 0.0
      CALL POPREAL8ARRAY(uli, 3)
      CALL NORMALIZE_B(li, lib, uli, ulib)
      CALL POPREAL8ARRAY(li, 3)
      CALL CROSS_B(vlocal(:, ii), vlocalb(:, ii), si(:, ii), sib(:, ii)&
&            , li, lib)
      tempb = rho*0.5*fairfmb
      vlocalmb = 2*vlocalm*areas(ii)*cl*tempb
      tempb0 = vlocalm**2*tempb
      areasb(ii) = areasb(ii) + cl*tempb0
      clb = areas(ii)*tempb0
      CALL POPREAL8(vlocalm)
      CALL NORM_B(vlocal(:, ii), vlocalb(:, ii), vlocalm, vlocalmb)
      alphalocalb(ii) = alphalocalb(ii) + cla(ii)*clb
    END DO
  END SUBROUTINE COMPUTE_AIRFOIL_FORCES_B

!============================================================
  SUBROUTINE COMPUTE_AIRFOIL_FORCES(n_vort, rho, cl0, cla, areas, vlocal&
&   , alphalocal, si, fairf)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, cl0(n_vort), cla(n_vort), areas(n_vort)
    REAL, INTENT(IN) :: vlocal(3, n_vort), alphalocal(n_vort), si(3, &
&   n_vort)
! Output variables
    REAL, INTENT(OUT) :: fairf(3, n_vort)
! Working variables
    REAL :: fairfm, cl, li(3), uli(3), vlocalm
    INTEGER :: ii
! EXECUTION
! Loop over all horseshoe vortices
    DO ii=1,n_vort
! Compute the magnitude of the force given by the 2D section
! L = 0.5*Vlocal²*area*cl
      cl = cl0(ii) + alphalocal(ii)*cla(ii)
      CALL NORM(vlocal(:, ii), vlocalm)
      fairfm = 0.5*rho*vlocalm*vlocalm*areas(ii)*cl
! Get normalized lift direction
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
      CALL NORMALIZE(li, uli)
! Store the force
      fairf(:, ii) = fairfm*uli
    END DO
  END SUBROUTINE COMPUTE_AIRFOIL_FORCES

!  Differentiation of get_residuals in reverse (adjoint) mode:
!   gradient     of useful results: res x twist gama
!   with respect to varying inputs: res x twist gama
!============================================================
  SUBROUTINE GET_RESIDUALS_B0(n_vort, x, xb, gama, gamab, twist, twistb&
&   , chords, cl0, cla, vinf, rho, res, resb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL :: gamab(n_vort), twistb(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL :: res(n_vort)
    REAL :: resb(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: aicb(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: uaib(3, n_vort), unib(3, n_vort), sib(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: areasb(n_vort), vlocalb(3, n_vort), alphalocalb(n_vort)
    REAL :: fcirc(3, n_vort), fairf(3, n_vort), deltaf(3)
    REAL :: fcircb(3, n_vort), fairfb(3, n_vort), deltafb(3)
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL PUSHREAL8ARRAY(uai, 3*n_vort)
    CALL GET_GEOM_VECTORS(n_vort, x, twist, chords, uai, uni, si, areas)
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get circulation forces
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Get airfoil forces
    CALL COMPUTE_AIRFOIL_FORCES(n_vort, rho, cl0, cla, areas, vlocal, &
&                         alphalocal, si, fairf)
    fairfb = 0.0
    fcircb = 0.0
    DO ii=n_vort,1,-1
      deltaf = fcirc(:, ii) - fairf(:, ii)
      deltafb = 0.0
      deltafb(1) = deltafb(1) + 2*deltaf(1)*resb(ii)
      deltafb(2) = deltafb(2) + 2*deltaf(2)*resb(ii)
      deltafb(3) = deltafb(3) + 2*deltaf(3)*resb(ii)
      resb(ii) = 0.0
      fcircb(:, ii) = fcircb(:, ii) + deltafb
      fairfb(:, ii) = fairfb(:, ii) - deltafb
    END DO
    CALL COMPUTE_AIRFOIL_FORCES_B(n_vort, rho, cl0, cla, areas, areasb, &
&                           vlocal, vlocalb, alphalocal, alphalocalb, si&
&                           , sib, fairf, fairfb)
    CALL COMPUTE_CIRCULATION_FORCES_B(n_vort, rho, vlocal, vlocalb, si, &
&                               sib, gama, gamab, fcirc, fcircb)
    CALL GET_LOCAL_VELS_B(n_vort, gama, gamab, aic, aicb, vinf, uai, &
&                   uaib, uni, unib, vlocal, vlocalb, alphalocal, &
&                   alphalocalb)
    CALL POPREAL8ARRAY(uai, 3*n_vort)
    CALL GET_GEOM_VECTORS_B(n_vort, x, xb, twist, twistb, chords, uai, &
&                     uaib, uni, unib, si, sib, areas, areasb)
    CALL GET_AIC_MATRIX_B(n_vort, x, xb, uinf, aic, aicb)
  END SUBROUTINE GET_RESIDUALS_B0

!============================================================
  SUBROUTINE GET_RESIDUALS(n_vort, x, gama, twist, chords, cl0, cla, &
&   vinf, rho, res)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: fcirc(3, n_vort), fairf(3, n_vort), deltaf(3)
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL GET_GEOM_VECTORS(n_vort, x, twist, chords, uai, uni, si, areas)
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get circulation forces
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Get airfoil forces
    CALL COMPUTE_AIRFOIL_FORCES(n_vort, rho, cl0, cla, areas, vlocal, &
&                         alphalocal, si, fairf)
! The residual is the difference between the forces for each horseshoe vortex
    DO ii=1,n_vort
! Get the difference in forces
      deltaf = fcirc(:, ii) - fairf(:, ii)
! The residual is the magnitude of the difference
      res(ii) = deltaf(1)**2 + deltaf(2)**2 + deltaf(3)**2
    END DO
  END SUBROUTINE GET_RESIDUALS

!  Differentiation of get_functions in reverse (adjoint) mode:
!   gradient     of useful results: d loads l sref
!   with respect to varying inputs: x twist gama
!============================================================
  SUBROUTINE GET_FUNCTIONS_B0(n_vort, x, xb, gama, gamab, twist, twistb&
&   , chords, cl0, cla, vinf, rho, sref, srefb, cl, cd, l, lb, d, db, &
&   loads, loadsb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL :: gamab(n_vort), twistb(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL :: sref, cl, cd, l, d, loads(n_vort)
    REAL :: srefb, lb, db, loadsb(n_vort)
! Working variables
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uinfb(3), aicb(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: uaib(3, n_vort), unib(3, n_vort), sib(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: areasb(n_vort), vlocalb(3, n_vort), alphalocalb(n_vort)
    REAL :: fcirc(3, n_vort), fbody(3), fbodym, vinfm
    REAL :: fcircb(3, n_vort), fbodyb(3), fbodymb
    INTEGER :: ii
    INTRINSIC SQRT
    REAL :: tempb
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL PUSHREAL8ARRAY(uai, 3*n_vort)
    CALL GET_GEOM_VECTORS(n_vort, x, twist, chords, uai, uni, si, areas)
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get forces on every bound vortex
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Store bending forces
! Get total area and forces in the system of coordinates of the body
    fbody = 0.0
    DO ii=1,n_vort
      fbody(1) = fbody(1) + fcirc(1, ii)
      fbody(2) = fbody(2) + fcirc(2, ii)
      fbody(3) = fbody(3) + fcirc(3, ii)
    END DO
! The drag is aligned with the free-stream
    CALL DOT(fbody, uinf, d)
! The rest is the lift force
    CALL NORM(fbody, fbodym)
! Make results non dimensional
    IF (fbodym**2 - d**2 .EQ. 0.0) THEN
      tempb = 0.0
    ELSE
      tempb = lb/(2.0*SQRT(fbodym**2-d**2))
    END IF
    fbodymb = 2*fbodym*tempb
    db = db - 2*d*tempb
    fbodyb = 0.0
    CALL NORM_B(fbody, fbodyb, fbodym, fbodymb)
    uinfb = 0.0
    CALL DOT_B(fbody, fbodyb, uinf, uinfb, d, db)
    fcircb = 0.0
    areasb = 0.0
    DO ii=n_vort,1,-1
      fcircb(3, ii) = fcircb(3, ii) + fbodyb(3)
      fcircb(2, ii) = fcircb(2, ii) + fbodyb(2)
      fcircb(1, ii) = fcircb(1, ii) + fbodyb(1)
      areasb(ii) = areasb(ii) + srefb
    END DO
    fcircb(3, :) = fcircb(3, :) + loadsb
    vlocalb = 0.0
    sib = 0.0
    gamab = 0.0
    CALL COMPUTE_CIRCULATION_FORCES_B(n_vort, rho, vlocal, vlocalb, si, &
&                               sib, gama, gamab, fcirc, fcircb)
    alphalocalb = 0.0
    CALL GET_LOCAL_VELS_B(n_vort, gama, gamab, aic, aicb, vinf, uai, &
&                   uaib, uni, unib, vlocal, vlocalb, alphalocal, &
&                   alphalocalb)
    CALL POPREAL8ARRAY(uai, 3*n_vort)
    xb = 0.0
    twistb = 0.0
    uaib = 0.0
    unib = 0.0
    CALL GET_GEOM_VECTORS_B(n_vort, x, xb, twist, twistb, chords, uai, &
&                     uaib, uni, unib, si, sib, areas, areasb)
    CALL GET_AIC_MATRIX_B(n_vort, x, xb, uinf, aic, aicb)
  END SUBROUTINE GET_FUNCTIONS_B0

!============================================================
  SUBROUTINE GET_FUNCTIONS(n_vort, x, gama, twist, chords, cl0, cla, &
&   vinf, rho, sref, cl, cd, l, d, loads)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: sref, cl, cd, l, d, loads(n_vort)
! Working variables
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: fcirc(3, n_vort), fbody(3), fbodym, vinfm
    INTEGER :: ii
    INTRINSIC SQRT
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL GET_GEOM_VECTORS(n_vort, x, twist, chords, uai, uni, si, areas)
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get forces on every bound vortex
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Store bending forces
    loads = fcirc(3, :)
! Get total area and forces in the system of coordinates of the body
    sref = 0.0
    fbody = 0.0
    DO ii=1,n_vort
      sref = sref + areas(ii)
      fbody(1) = fbody(1) + fcirc(1, ii)
      fbody(2) = fbody(2) + fcirc(2, ii)
      fbody(3) = fbody(3) + fcirc(3, ii)
    END DO
! The drag is aligned with the free-stream
    CALL DOT(fbody, uinf, d)
! The rest is the lift force
    CALL NORM(fbody, fbodym)
    l = SQRT(fbodym*fbodym - d*d)
! Make results non dimensional
    CALL NORM(vinf, vinfm)
    cl = 2.0*l/sref/vinfm/vinfm/rho
    cd = 2.0*d/sref/vinfm/vinfm/rho
  END SUBROUTINE GET_FUNCTIONS

!  Differentiation of norm in reverse (adjoint) mode:
!   gradient     of useful results: am a
!   with respect to varying inputs: a
!============================================================
  SUBROUTINE NORM_B(a, ab, am, amb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL :: ab(3)
    REAL :: am
    REAL :: amb
    INTRINSIC SQRT
    REAL :: tempb
    IF (a(1)**2 + a(2)**2 + a(3)**2 .EQ. 0.0) THEN
      tempb = 0.0
    ELSE
      tempb = amb/(2.0*SQRT(a(1)**2+a(2)**2+a(3)**2))
    END IF
    ab(1) = ab(1) + 2*a(1)*tempb
    ab(2) = ab(2) + 2*a(2)*tempb
    ab(3) = ab(3) + 2*a(3)*tempb
  END SUBROUTINE NORM_B

!============================================================
  SUBROUTINE NORM(a, am)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(OUT) :: am
    INTRINSIC SQRT
    am = SQRT(a(1)*a(1) + a(2)*a(2) + a(3)*a(3))
  END SUBROUTINE NORM

!  Differentiation of normalize in reverse (adjoint) mode:
!   gradient     of useful results: an a
!   with respect to varying inputs: a
!============================================================
  SUBROUTINE NORMALIZE_B(a, ab, an, anb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL :: ab(3)
    REAL :: an(3)
    REAL :: anb(3)
    REAL :: am
    REAL :: amb
    CALL NORM(a, am)
    ab = ab + anb/am
    amb = -(SUM(a*anb)/am**2)
    CALL NORM_B(a, ab, am, amb)
  END SUBROUTINE NORMALIZE_B

!============================================================
  SUBROUTINE NORMALIZE(a, an)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(OUT) :: an(3)
    REAL :: am
    CALL NORM(a, am)
    an = a/am
  END SUBROUTINE NORMALIZE

!  Differentiation of dot in reverse (adjoint) mode:
!   gradient     of useful results: adb a b
!   with respect to varying inputs: a b
!============================================================
  SUBROUTINE DOT_B(a, ab, b, bb, adb, adbb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL :: ab(3), bb(3)
    REAL :: adb
    REAL :: adbb
    ab(1) = ab(1) + b(1)*adbb
    bb(1) = bb(1) + a(1)*adbb
    ab(2) = ab(2) + b(2)*adbb
    bb(2) = bb(2) + a(2)*adbb
    ab(3) = ab(3) + b(3)*adbb
    bb(3) = bb(3) + a(3)*adbb
  END SUBROUTINE DOT_B

!============================================================
  SUBROUTINE DOT(a, b, adb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(OUT) :: adb
    adb = a(1)*b(1) + a(2)*b(2) + a(3)*b(3)
  END SUBROUTINE DOT

!  Differentiation of cross in reverse (adjoint) mode:
!   gradient     of useful results: acb a b
!   with respect to varying inputs: acb a b
!============================================================
  SUBROUTINE CROSS_B(a, ab, b, bb, acb, acbb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL :: ab(3), bb(3)
    REAL :: acb(3)
    REAL :: acbb(3)
    ab(1) = ab(1) + b(2)*acbb(3) - b(3)*acbb(2)
    bb(2) = bb(2) + a(1)*acbb(3) - a(3)*acbb(1)
    ab(2) = ab(2) + b(3)*acbb(1) - b(1)*acbb(3)
    bb(1) = bb(1) + a(3)*acbb(2) - a(2)*acbb(3)
    acbb(3) = 0.0
    ab(3) = ab(3) + b(1)*acbb(2) - b(2)*acbb(1)
    bb(3) = bb(3) + a(2)*acbb(1) - a(1)*acbb(2)
    acbb(2) = 0.0
    acbb(1) = 0.0
  END SUBROUTINE CROSS_B

!============================================================
  SUBROUTINE CROSS(a, b, acb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(OUT) :: acb(3)
    acb(1) = a(2)*b(3) - a(3)*b(2)
    acb(2) = a(3)*b(1) - a(1)*b(3)
    acb(3) = a(1)*b(2) - a(2)*b(1)
  END SUBROUTINE CROSS

!  Differentiation of llt_main in reverse (adjoint) mode:
!   gradient     of useful results: d res loads l sref
!   with respect to varying inputs: res x twist gama
!============================================================
  SUBROUTINE LLT_MAIN_B(n_vort, x, xb, gama, gamab, twist, twistb, &
&   chords, cl0, cla, vinf, rho, res, resb, sref, srefb, cl, cd, l, lb, &
&   d, db, loads, loadsb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL :: gamab(n_vort), twistb(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL :: res(n_vort), sref, cl, cd, l, d
    REAL :: resb(n_vort), srefb, lb, db
    REAL :: loads(n_vort)
    REAL :: loadsb(n_vort)
! EXECUTION
! Call relevant subroutines
    CALL GET_FUNCTIONS_B0(n_vort, x, xb, gama, gamab, twist, twistb, &
&                   chords, cl0, cla, vinf, rho, sref, srefb, cl, cd, l&
&                   , lb, d, db, loads, loadsb)
    CALL GET_RESIDUALS_B0(n_vort, x, xb, gama, gamab, twist, twistb, &
&                   chords, cl0, cla, vinf, rho, res, resb)
  END SUBROUTINE LLT_MAIN_B

!============================================================
  SUBROUTINE LLT_MAIN(n_vort, x, gama, twist, chords, cl0, cla, vinf, &
&   rho, res, sref, cl, cd, l, d, loads)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), twist(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort), sref, cl, cd, l, d
    REAL, INTENT(OUT) :: loads(n_vort)
! EXECUTION
! Call relevant subroutines
    CALL GET_RESIDUALS(n_vort, x, gama, twist, chords, cl0, cla, vinf, &
&                rho, res)
    CALL GET_FUNCTIONS(n_vort, x, gama, twist, chords, cl0, cla, vinf, &
&                rho, sref, cl, cd, l, d, loads)
  END SUBROUTINE LLT_MAIN

END MODULE LLT_MODULE_B

