""""
    Author: Widmark Kauê Silva Cardoso
    
    Question 2 from Homework 1:
        - Lifting line theory implementation in Fortran
        
"""
#%%----------------------------------------------------------
### Imports
import numpy as np
import matplotlib.pyplot as plt
import os 

from matplotlib.gridspec import GridSpec
from scipy.optimize import root
from functools import partial
from pathlib import Path

from utils import set_aiaa_style
# fortran module generated by f2py
from llt_f90 import llt  # type: ignore

#%%----------------------------------------------------------
### Clear screen
os.system('clear') # for linux

#%%----------------------------------------------------------
### plot settings
set_aiaa_style(16)

dpi = 600
format = 'pdf'
saveflag = True
#%%----------------------------------------------------------
### Path settings
rootdir = Path('.')
if not rootdir.absolute().name == 'homework01':
    rootdir = Path('.','homework01')

datadir = rootdir.joinpath('data')
datadir.mkdir(exist_ok=True, parents=True)
print("Data will be saved in:", datadir)

imagdir = rootdir.joinpath('images')
imagdir.mkdir(exist_ok=True, parents=True)
print("Images will be saved in:", imagdir)

#%%----------------------------------------------------------
### Input test
twist = np.array([0., 0., 0., 0., 0., 0.])
gama = np.array([1., 1., 1., 1., 1., 1.])
span = 8.0
chord = 1.0
cl0 = 0.0
cla = 6.283185307179586
alpha = 0.08726646259971647 # 5 degrees in radians
vinf = 10
rho_air = 1.225

inputs = dict(
    twist=twist,
    span=span,
    chord=chord,
    cl0=cl0,
    cla=cla,
    alpha=alpha,
    vinf=vinf,
    rho_air=rho_air
)

res_llt, cl, cd = llt.llt_main(gama=gama, **inputs)
print(50 * '-')
print("Results from Fortran:")
print("Lift coefficient (cl):", cl)
print("Drag coefficient (cd):", cd) 
print('Residues of the solution:', res_llt)

#%%----------------------------------------------------------
### Test solve LLT for gamma
def llt_residuals_only(gama, twist, span, chord, cl0, cla, alpha, vinf, rho_air):
    res_llt, _, _ = llt.llt_main(twist, gama, span, chord, cl0, cla, alpha, vinf, rho_air)
    return res_llt

# Create partial function with fixed parameters (all except gama)
llt_fixed_params = partial(llt_residuals_only, **inputs)

# gamma = np.array([2.01817096, 2.30589556, 2.38509966, 2.38509966, 2.30589556, 2.01817096])
sol = root(llt_fixed_params, gama)
res_llt, cl, cd = llt.llt_main(gama=sol.x, **inputs)
print(50 * '-')
print("Results from Fortran with solved gamma:")
print('Gamma values:', sol.x)
print("Lift coefficient (cl):", cl)
print("Drag coefficient (cd):", cd)
print('Residues of the solution:', res_llt)
#%%----------------------------------------------------------
### a) Solve LLT with 4 and 8 vortices
COEFF = np.zeros((4,8))

###
# 4 Vortices 
###
# Create partial function with fixed parameters (all except gama)
inputs_4v = inputs.copy()
inputs_4v['twist'] = np.zeros(4, dtype=float)
llt_4v_fixed_params = partial(llt_residuals_only, **inputs_4v)


sol_4v = root(llt_4v_fixed_params, np.ones(4, dtype=float))
res_llt, cl, cd = llt.llt_main(gama=sol_4v.x, **inputs_4v)
COEFF[0, :2] = [cl, cd]
COEFF[1, :4] = sol_4v.x

print(50 * '-')
print("Results from 4 vortices:")
print('Gamma values:', sol_4v.x)
print("Lift coefficient (cl):", cl)
print("Drag coefficient (cd):", cd)
print('Residues of the solution:', res_llt)

###
# 8 Vortices 
###
# Create partial function with fixed parameters (all except gama)
inputs_8v = inputs.copy()
inputs_8v['twist'] = np.zeros(8, dtype=float)
llt_8v_fixed_params = partial(llt_residuals_only, **inputs_8v)


sol_8v = root(llt_8v_fixed_params, np.ones(8, dtype=float))
res_llt, cl, cd = llt.llt_main(gama=sol_8v.x, **inputs_8v)
COEFF[2, :2] = [cl, cd]
COEFF[3, :8] = sol_8v.x

print(50 * '-')
print("Results from 8 vortices:")
print('Gamma values:', sol_8v.x)
print("Lift coefficient (cl):", cl)
print("Drag coefficient (cd):", cd)
print('Residues of the solution:', res_llt)

if saveflag:
    COEFF = np.round(COEFF, 8)
    COEFF_TXT = np.where(COEFF == 0, '', COEFF.astype(str))
    np.savetxt(datadir / 'coefficients_4_and_8_vortices.txt', 
            COEFF_TXT, 
            fmt='%4s', 
            header='cl cd \n gamma_values', 
            delimiter='\t')

#%%----------------------------------------------------------
### b) Compare LLT with 20 vortices to elipitical lift distribution

# Solve LLT with 20 vortices
nv = 20
inputs_20v = inputs.copy()
inputs_20v['twist'] = np.zeros(nv, dtype=float)
llt_20v_fixed_params = partial(llt_residuals_only, **inputs_20v)
sol_20v = root(llt_20v_fixed_params, np.ones(nv, dtype=float))
res_llt, cl, cd = llt.llt_main(gama=sol_20v.x, **inputs_20v)

print(50 * '-')
print("Results from 20 vortices:")
print('Gamma values:', sol_20v.x)
print("Lift coefficient (cl):", cl)
print("Drag coefficient (cd):", cd)
print('Residues of the solution:', res_llt)

# Implement elliptical lift distribution
Sref = span * chord
y = np.linspace(-span/2, span/2, nv)
gamma_0 = 2*vinf*Sref/(np.pi*span) * cl
gamma_elliptical = 2*gamma_0 * np.sqrt((0.5+ y/span) * (0.5-y/span))
CD = cl**2*Sref/(np.pi*span**2)

print('Results from elliptical wing:')
print('Gamma values:', gamma_elliptical)
print("Lift coefficient (CL):", cl)
print("Drag coefficient (CD):", CD)


plt.figure(figsize=(6,4))
plt.plot(y, gamma_elliptical,'k--', label='Elliptical distribution')
plt.plot(np.linspace(-span/2, span/2, nv), sol_20v.x, '-', color = 'darkblue', label='LLT with 20 vortices')

plt.xlabel('Spanwise location [m]')
plt.ylabel(r'$\Gamma$ [m$^2$/s]')

plt.legend()
plt.savefig(imagdir / f'q2_b.{format}', dpi=dpi, bbox_inches='tight') if saveflag else None

# plt.show()
#%%----------------------------------------------------------
### c) Plot the convergence history of the LLT solver for 20 vortices

nvVec = np.arange(4, 252, 2)
clVec = np.zeros_like(nvVec, dtype=float)
cdVec = np.zeros_like(nvVec, dtype=float)
print(50 * '-')
for i, nv in enumerate(nvVec):
    inputs_nv = inputs.copy()
    inputs_nv['twist'] = np.zeros(nv, dtype=float)
    llt_nv_fixed_params = partial(llt_residuals_only, **inputs_nv)
    sol_nv = root(llt_nv_fixed_params, np.ones(nv, dtype=float))
    res_llt, cl, cd = llt.llt_main(gama=sol_nv.x, **inputs_nv)
    clVec[i] = cl
    cdVec[i] = cd
    print(f"Number of vortices: {nv}, Residues: {np.sqrt(np.mean(res_llt**2))}, cl: {cl:.8f}, cd: {cd:.8f}")

clDiff = np.abs(np.diff(clVec))/clVec[1:]
cdDiff = np.abs(np.diff(cdVec))/cdVec[1:]

idx_cl = np.searchsorted(clDiff, 1e-5)
idx_cd = np.searchsorted(cdDiff, 1e-5)
print(50 * '-')
print(f'Final results with tol = 1e-5: cl = {clVec[idx_cl]:.5f}, cd = {cdVec[idx_cd]:.8f}')

#### Plotting convergence history of CL and CD with number of vortices
fig = plt.figure(figsize=(12,5))

gs = GridSpec(2, 2, figure=fig)
ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[1, 0])
ax3 = fig.add_subplot(gs[:, 1])

# Plot CL
ax1.plot(nvVec, clVec, 'ko-', label='Lift Coefficient (cl)')
ax1.set_xlabel('Number of Vortices')
ax1.set_ylabel(r'$C_L$')

ax1.set_title('(a)')
ax1.grid()

# Plot CD
ax2.plot(nvVec, cdVec, 'ks-', label='Drag Coefficient (cd)')
ax2.set_xlabel('Number of Vortices')
ax2.set_ylabel(r'$C_D$')
ax2.set_title('(b)')
ax2.grid()

# Plot differences
ax3.loglog(nvVec[:-1], clDiff, 'o-',color = 'darkred', label=r'Error $C_L$')
ax3.loglog(nvVec[:-1], cdDiff, 's-',color = 'darkblue', label=r'Error $C_D$')

ax3.set_xlabel('Number of Vortices')
ax3.set_ylabel(r'Relative Difference')
ax3.set_title('(c)')
ax3.legend()
ax3.grid()

plt.tight_layout()
plt.savefig(imagdir / f'q2_c.{format}', dpi=dpi, bbox_inches='tight') if saveflag else None
plt.show()