!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 20 Jun 2026 11:35
!
MODULE LLT_D
  IMPLICIT NONE

CONTAINS
!  Differentiation of llt_main in forward (tangent) mode:
!   variations   of useful results: cd cl res_llt
!   with respect to varying inputs: twist gama
!   RW status of diff variables: twist:in gama:in cd:out cl:out
!                res_llt:out
  SUBROUTINE LLT_MAIN_D(nelem, twist, twistd, gama, gamad, span, chord, &
&   cl0, cla, alpha, vinf, rho_air, res_llt, res_lltd, cl, cld, cd, cdd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: nelem
    REAL, INTENT(IN) :: twist(nelem), gama(nelem)
    REAL, INTENT(IN) :: twistd(nelem), gamad(nelem)
    REAL, INTENT(IN) :: span, chord, cl0, cla, alpha, vinf, rho_air
! Output variables
    REAL, INTENT(OUT) :: res_llt(nelem)
    REAL, INTENT(OUT) :: res_lltd(nelem)
    REAL, INTENT(OUT) :: cl, cd
    REAL, INTENT(OUT) :: cld, cdd
! Working variables
    INTEGER :: ii
    REAL :: pi
    REAL :: panel_length, sref
! Spanwise locations of the horseshoe vortices
    REAL :: yc(nelem)
! Induced velocity at each horseshoe vortex and efective velocity at each wing section
    REAL :: wi(nelem), veff(nelem)
    REAL :: wid(nelem), veffd(nelem)
! Induced angle of attack and effective angle of attack at each wing section
    REAL :: alpha_ind(nelem), alpha_eff(nelem)
    REAL :: alpha_indd(nelem), alpha_effd(nelem)
! Section lift coefficient, sectional lift force and Kutta-Joukowski force at each wing section
    REAL :: cli(nelem), lsi(nelem), lki(nelem)
    REAL :: clid(nelem), lsid(nelem), lkid(nelem)
! Index array for the horseshoe vortices
    REAL :: idx(nelem)
    INTRINSIC ACOS
    INTRINSIC REAL
    INTRINSIC SUM
    INTRINSIC ATAN
    INTRINSIC SQRT
    INTRINSIC COS
    INTRINSIC SIN
    REAL, DIMENSION(nelem) :: arg1
    REAL, DIMENSION(nelem) :: arg1d
    REAL, DIMENSION(nelem) :: temp
    REAL :: temp0
! EXECUTION
! Constants
    pi = ACOS(-1.0)
    panel_length = span/REAL(nelem)
    sref = span*chord
    idx = (/(1.0+(ii-1)*1.0, ii=1,nelem)/)
! ADD YOUR CODE HERE 
! Spanwise locations of the horseshoe vortices
    yc = 0.5*(panel_length-span) + (idx-1)*panel_length
    wid = 0.0
! Compute the induced velocity at each horseshoe vortex using the Biot-Savart law
    DO ii=1,nelem
! Induced velocity at each horseshoe vortex
      temp = 4*((yc(ii)-yc)*(yc(ii)-yc)) - panel_length*panel_length
      arg1d = gamad/temp
      arg1 = gama/temp
      wid(ii) = panel_length*SUM(arg1d)/pi
      wi(ii) = panel_length/pi*SUM(arg1)
    END DO
! Compute the induced AoA, effective AoA and effective velocity at each wing section
! Induced angle of attack at each wing section
    alpha_indd = wid/((1.0+(wi/vinf)**2)*vinf)
    alpha_ind = ATAN(wi/vinf)
! Effective angle of attack at each wing section
    alpha_effd = twistd + alpha_indd
    alpha_eff = alpha + twist + alpha_ind
! Effective velocity at each wing section
    arg1d = 2*wi*wid
    arg1 = vinf**2 + wi**2
    temp = SQRT(arg1)
    WHERE (arg1 .EQ. 0.0) 
      veffd = 0.0
    ELSEWHERE
      veffd = arg1d/(2.0*temp)
    END WHERE
    veff = temp
! Section lift coefficient at each wing section
    clid = cla*alpha_effd
    cli = cl0 + cla*alpha_eff
! Compute lift force at each section 
! Sectional lift force at each wing section
    temp0 = 0.5*rho_air*chord
    lsid = temp0*(cli*2*veff*veffd+veff**2*clid)
    lsi = temp0*(veff*veff*cli)
! Kutta-Joukowski force at each wing section
    lkid = rho_air*(gama*veffd+veff*gamad)
    lki = rho_air*veff*gama
! Compute the LLT residuals at each wing section
! LLT residuals at each wing section
    res_lltd = lsid - lkid
    res_llt = lsi - lki
! Compute the total lift and drag coefficients of the wing
! Total lift coefficient of the wing
    temp = COS(alpha_ind)
    arg1d = panel_length*(temp*lkid-lki*SIN(alpha_ind)*alpha_indd)
    arg1 = panel_length*(lki*temp)
    temp0 = 0.5*rho_air*sref*(vinf*vinf)
    cld = SUM(arg1d)/temp0
    cl = SUM(arg1)/temp0
! Total drag coefficient of the wing
    temp = SIN(alpha_ind)
    arg1d = panel_length*(temp*lkid+lki*COS(alpha_ind)*alpha_indd)
    arg1 = panel_length*(lki*temp)
    temp0 = 0.5*rho_air*sref*(vinf*vinf)
    cdd = -(SUM(arg1d)/temp0)
    cd = -(SUM(arg1)/temp0)
! END OF YOUR CODE
  END SUBROUTINE LLT_MAIN_D

  SUBROUTINE LLT_MAIN(nelem, twist, gama, span, chord, cl0, cla, alpha, &
&   vinf, rho_air, res_llt, cl, cd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: nelem
    REAL, INTENT(IN) :: twist(nelem), gama(nelem)
    REAL, INTENT(IN) :: span, chord, cl0, cla, alpha, vinf, rho_air
! Output variables
    REAL, INTENT(OUT) :: res_llt(nelem)
    REAL, INTENT(OUT) :: cl, cd
! Working variables
    INTEGER :: ii
    REAL :: pi
    REAL :: panel_length, sref
! Spanwise locations of the horseshoe vortices
    REAL :: yc(nelem)
! Induced velocity at each horseshoe vortex and efective velocity at each wing section
    REAL :: wi(nelem), veff(nelem)
! Induced angle of attack and effective angle of attack at each wing section
    REAL :: alpha_ind(nelem), alpha_eff(nelem)
! Section lift coefficient, sectional lift force and Kutta-Joukowski force at each wing section
    REAL :: cli(nelem), lsi(nelem), lki(nelem)
! Index array for the horseshoe vortices
    REAL :: idx(nelem)
    INTRINSIC ACOS
    INTRINSIC REAL
    INTRINSIC SUM
    INTRINSIC ATAN
    INTRINSIC SQRT
    INTRINSIC COS
    INTRINSIC SIN
    REAL, DIMENSION(nelem) :: arg1
! EXECUTION
! Constants
    pi = ACOS(-1.0)
    panel_length = span/REAL(nelem)
    sref = span*chord
    idx = (/(1.0+(ii-1)*1.0, ii=1,nelem)/)
! ADD YOUR CODE HERE 
! Spanwise locations of the horseshoe vortices
    yc = 0.5*(panel_length-span) + (idx-1)*panel_length
! Compute the induced velocity at each horseshoe vortex using the Biot-Savart law
    DO ii=1,nelem
! Induced velocity at each horseshoe vortex
      arg1 = gama/(4*(yc(ii)-yc)**2-panel_length**2)
      wi(ii) = panel_length/pi*SUM(arg1)
    END DO
! Compute the induced AoA, effective AoA and effective velocity at each wing section
! Induced angle of attack at each wing section
    alpha_ind = ATAN(wi/vinf)
! Effective angle of attack at each wing section
    alpha_eff = alpha + twist + alpha_ind
! Effective velocity at each wing section
    arg1 = vinf**2 + wi**2
    veff = SQRT(arg1)
! Section lift coefficient at each wing section
    cli = cl0 + cla*alpha_eff
! Compute lift force at each section 
! Sectional lift force at each wing section
    lsi = 0.5*rho_air*veff**2*chord*cli
! Kutta-Joukowski force at each wing section
    lki = rho_air*veff*gama
! Compute the LLT residuals at each wing section
! LLT residuals at each wing section
    res_llt = lsi - lki
! Compute the total lift and drag coefficients of the wing
! Total lift coefficient of the wing
    arg1 = lki*panel_length*COS(alpha_ind)
    cl = SUM(arg1)/(0.5*rho_air*vinf**2*sref)
! Total drag coefficient of the wing
    arg1 = lki*panel_length*SIN(alpha_ind)
    cd = -(SUM(arg1)/(0.5*rho_air*vinf**2*sref))
! END OF YOUR CODE
  END SUBROUTINE LLT_MAIN

END MODULE LLT_D

