!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 24 Mar 2026 19:29
!
! fem_module.f90
! module with FEM problem implementation
MODULE FEM_MODULE_D
  IMPLICIT NONE

CONTAINS
!  Differentiation of get_residuals in forward (tangent) mode:
!   variations   of useful results: res
!   with respect to varying inputs: d a
  SUBROUTINE GET_RESIDUALS_D(n_bars, a, ad, d, dd, res, resd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
    REAL, INTENT(IN) :: ad(n_bars), dd(n_bars)
! Output variables
    REAL, INTENT(OUT) :: res(n_bars)
    REAL, INTENT(OUT) :: resd(n_bars)
! Working variables
    INTEGER :: ii
    REAL :: k(n_bars, n_bars), f(n_bars), kd(n_bars)
    REAL :: kd0(n_bars, n_bars), kdd(n_bars)
! EXECUTION
!!! Build stiffness matrix
    k = 0.0
! Contribution of the first bar
    kd0 = 0.0
    kd0(1, 1) = ad(1)
    k(1, 1) = a(1)
! Contribution of remaining bars
    DO ii=2,n_bars
      kd0(ii-1, ii-1) = kd0(ii-1, ii-1) + ad(ii)
      k(ii-1, ii-1) = k(ii-1, ii-1) + a(ii)
      kd0(ii-1, ii) = kd0(ii-1, ii) - ad(ii)
      k(ii-1, ii) = k(ii-1, ii) - a(ii)
      kd0(ii, ii-1) = kd0(ii, ii-1) - ad(ii)
      k(ii, ii-1) = k(ii, ii-1) - a(ii)
      kd0(ii, ii) = kd0(ii, ii) + ad(ii)
      k(ii, ii) = k(ii, ii) + a(ii)
    END DO
! Multiply by the 1/L_bar factor
! In this problem L_bar = 1/n_bars
    kd0 = n_bars*kd0
    k = k*n_bars
!!! Build force vector (load/length = 1)
    f = 1.0/n_bars
    f(n_bars) = 0.5/n_bars
!!! Compute residuals
    kdd = 0.0
    CALL MATDOTVEC_D(n_bars, k, kd0, d, dd, kd, kdd)
    resd = kdd
    res = kd - f
  END SUBROUTINE GET_RESIDUALS_D

  SUBROUTINE GET_RESIDUALS(n_bars, a, d, res)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
! Output variables
    REAL, INTENT(OUT) :: res(n_bars)
! Working variables
    INTEGER :: ii
    REAL :: k(n_bars, n_bars), f(n_bars), kd(n_bars)
! EXECUTION
!!! Build stiffness matrix
    k = 0.0
! Contribution of the first bar
    k(1, 1) = a(1)
! Contribution of remaining bars
    DO ii=2,n_bars
      k(ii-1, ii-1) = k(ii-1, ii-1) + a(ii)
      k(ii-1, ii) = k(ii-1, ii) - a(ii)
      k(ii, ii-1) = k(ii, ii-1) - a(ii)
      k(ii, ii) = k(ii, ii) + a(ii)
    END DO
! Multiply by the 1/L_bar factor
! In this problem L_bar = 1/n_bars
    k = k*n_bars
!!! Build force vector (load/length = 1)
    f = 1.0/n_bars
    f(n_bars) = 0.5/n_bars
!!! Compute residuals
    CALL MATDOTVEC(n_bars, k, d, kd)
    res = kd - f
  END SUBROUTINE GET_RESIDUALS

!  Differentiation of get_functions in forward (tangent) mode:
!   variations   of useful results: v c
!   with respect to varying inputs: d a
!===================================
  SUBROUTINE GET_FUNCTIONS_D(n_bars, a, ad, d, dd, c, cd, v, vd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
    REAL, INTENT(IN) :: ad(n_bars), dd(n_bars)
! Output variables
    REAL, INTENT(OUT) :: c, v
    REAL, INTENT(OUT) :: cd, vd
! Working variables
    REAL :: f(n_bars)
    INTEGER :: ii
! EXECUTION
!!! Build force vector (load/length = 1)
    f = 1.0/n_bars
    f(n_bars) = 0.5/n_bars
!!! Compliance
    c = 0
!!! Volume
    v = 0
    vd = 0.0
    cd = 0.0
    DO ii=1,n_bars
      cd = cd + f(ii)*dd(ii)
      c = c + f(ii)*d(ii)
      vd = vd + ad(ii)
      v = v + a(ii)
    END DO
    vd = vd/n_bars
    v = v/n_bars
  END SUBROUTINE GET_FUNCTIONS_D

!===================================
  SUBROUTINE GET_FUNCTIONS(n_bars, a, d, c, v)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
! Output variables
    REAL, INTENT(OUT) :: c, v
! Working variables
    REAL :: f(n_bars)
    INTEGER :: ii
! EXECUTION
!!! Build force vector (load/length = 1)
    f = 1.0/n_bars
    f(n_bars) = 0.5/n_bars
!!! Compliance
    c = 0
!!! Volume
    v = 0
    DO ii=1,n_bars
      c = c + f(ii)*d(ii)
      v = v + a(ii)
    END DO
    v = v/n_bars
  END SUBROUTINE GET_FUNCTIONS

!  Differentiation of matdotvec in forward (tangent) mode:
!   variations   of useful results: kd
!   with respect to varying inputs: d k
!===================================
  SUBROUTINE MATDOTVEC_D(n, k, kd0, d, dd, kd, kdd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n
    REAL, INTENT(IN) :: k(n, n), d(n)
    REAL, INTENT(IN) :: kd0(n, n), dd(n)
! Output variables
    REAL, INTENT(OUT) :: kd(n)
    REAL, INTENT(OUT) :: kdd(n)
! Working variables
    INTEGER :: ii
! EXECUTION
    kd = 0.0
    kdd = 0.0
    DO ii=1,n
      kdd = kdd + d(ii)*kd0(:, ii) + k(:, ii)*dd(ii)
      kd = kd + k(:, ii)*d(ii)
    END DO
  END SUBROUTINE MATDOTVEC_D

!===================================
  SUBROUTINE MATDOTVEC(n, k, d, kd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n
    REAL, INTENT(IN) :: k(n, n), d(n)
! Output variables
    REAL, INTENT(OUT) :: kd(n)
! Working variables
    INTEGER :: ii
! EXECUTION
    kd = 0.0
    DO ii=1,n
      kd = kd + k(:, ii)*d(ii)
    END DO
  END SUBROUTINE MATDOTVEC

!  Differentiation of main in forward (tangent) mode:
!   variations   of useful results: res v c
!   with respect to varying inputs: d a
!   RW status of diff variables: res:out d:in v:out a:in c:out
!===================================
  SUBROUTINE MAIN_D(n_bars, a, ad, d, dd, res, resd, c, cd, v, vd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
    REAL, INTENT(IN) :: ad(n_bars), dd(n_bars)
! Output variables
    REAL, INTENT(OUT) :: res(n_bars)
    REAL, INTENT(OUT) :: resd(n_bars)
    REAL, INTENT(OUT) :: c, v
    REAL, INTENT(OUT) :: cd, vd
! EXECUTION
    CALL GET_RESIDUALS_D(n_bars, a, ad, d, dd, res, resd)
    CALL GET_FUNCTIONS_D(n_bars, a, ad, d, dd, c, cd, v, vd)
  END SUBROUTINE MAIN_D

!===================================
  SUBROUTINE MAIN(n_bars, a, d, res, c, v)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_bars
    REAL, INTENT(IN) :: a(n_bars), d(n_bars)
! Output variables
    REAL, INTENT(OUT) :: res(n_bars)
    REAL, INTENT(OUT) :: c, v
! EXECUTION
    CALL GET_RESIDUALS(n_bars, a, d, res)
    CALL GET_FUNCTIONS(n_bars, a, d, c, v)
  END SUBROUTINE MAIN

END MODULE FEM_MODULE_D

